sigstore/fulcio

.gitignore

The former regex was failing to capture .idea folders

Fix .idea/ regex

---

cmd/client/app/root.go
openapi.yaml
pkg/api/signing_cert.go
pkg/generated/models/submit_success.go
pkg/generated/restapi/embedded_spec.go

If we introduce intermediary CAs, we'll need these.

Add support for returning a cert chain with the response.

---

.gitignore
Makefile
cmd/client/app/root.go
cmd/server/app/root.go
go.sum
openapi.yaml
pkg/api/signing_cert.go
pkg/generated/restapi/configure_fulcio_server.go
pkg/generated/restapi/embedded_spec.go
pkg/generated/restapi/operations/fulcio_server_api.go
pkg/oauthflow/flow.go
pkg/oauthflow/flow_test.go
pkg/oauthflow/pkce.go

This change adds the use of the PKCE challenge and verifier into the
OAuth2 flow in the CLI to be compliant with RFC 8252. It also adds the
optional nonce parameter.
It also converts the Fulcio server to using the raw id_token as the
Authorization header Bearer token, and verifies that:
- the token was signed by the specified OIDC identity provider
- the client ID matches what is expected
- the email address in the id_token was verified at some point in past
This change also moves the OIDC settings into command line arguments,
and shrinks the number of HTTP calls used in the OAuth2 dance.
Signed-off-by: Bob Callaway <bcallawa@redhat.com>

Use 'Authorization Code with PKCE' OAuth2 flow

---

pkg/api/signing_cert.go
pkg/ca/ca.go

This will let tests pass since there are no credentials in GitHub Actions.

Use a once block instead of an init.

---

cmd/client/app/root.go
go.mod
go.sum
pkg/oauthflow/flow.go
pkg/oauthflow/pkce.go

Previously the code presumed the support of PKCE by a configured OIDC
identity provider. This patch verifies support from the OIDC discovery 
document and forces the use of the S256 method.
Also, OAuth2 state and nonce values (as well as the PKCE code verifier)
have been switched to using ksuid instead of simply random values to
improve protection against replay attacks.
Signed-off-by: Bob Callaway <bcallawa@redhat.com>

Improve PKCE code and use ksuid for state/nonce

---

.github/workflows/main.yml
go.mod
pkg/generated/client/operations/operations_client.go
pkg/generated/client/operations/signing_cert_parameters.go
pkg/generated/client/operations/signing_cert_responses.go
pkg/generated/models/certificate_request.go
pkg/generated/models/error.go
pkg/generated/restapi/operations/fulcio_server_api.go
pkg/generated/restapi/operations/signing_cert.go
pkg/generated/restapi/operations/signing_cert_parameters.go

Right now the build tries to detect mismatches between what is in the change versus any changes actually occurred from a clean rebuild (e.g. missed checking in any updates to generated code). However if those are present, the build logs print out the difference but do not cause the build to fail.
Also bumps GOVERSION to match what is used in Dockerfile so we don't have go.mod or go.sum as a reason for above.

fail build if diff exists

---

pkg/api/signing_cert.go

This makes local development a bit easier.

Skip the CT log upload if no ct server is configured.

---

cmd/app/root.go
pkg/generated/restapi/configure_fulcio_server.go

Allow for multiple OIDC providers.

---

pkg/ca/ca.go

This was overkill and the field is deprecated anyway. We only check the SAN.

Remove the common name field from the certs.

---

cmd/app/root.go
go.mod
go.sum

We're not using it, and I'm going to start adding an oauth config file
for issuers/client ids. These won't play nicely anyway with viper.

Remove the viper config code.

---

config/fulcio-config.yaml
pkg/api/error.go
pkg/api/signing_cert.go
pkg/ca/ca.go
pkg/challenges/challenges.go
pkg/challenges/challenges_test.go
pkg/config/config.go
pkg/generated/restapi/configure_fulcio_server.go

This also refactors the code a bit so each "issuer" can declare which
type of subject it will grant. The current types are email and spiffe.
Each type can set different fields in the final cert.

Support SPIFFE challenges instead of just emails.

---

.github/workflows/verify-k8s.yml
config/README.md
config/deployment.yaml
config/fulcio-config.yaml
config/private-ca-secret-ci.yaml

This PR adds some validation for the k8s manifests in the config directory and create a kind cluster to deploy the manifests and validate fulcio
this is just an initial work, more things can be added in the future
/assign @bobcallaway @dlorenc @lukehinds 
bob this is related to the PR opened https://github.com/sigstore/fulcio/pull/116

fulcio/e2e: add initial kind cluster deployment to test fulcio server

---

.github/workflows/verify-k8s.yml
.ko.yaml

Change the base image when building with `ko` this is needed because in this PR https://github.com/sigstore/fulcio/pull/115 we add some changes that require `CGO_ENABLED=1` and using the default base image we got some errors
Tested this with the changes in the PR above and it is working now.
- Also collect the cluster logs if we need to debug any issue
/assign @lukehinds @dlorenc 
Luke after we merge this you can rebase and then will work 😄

change base image for fulcio-server when building with ko

---

cmd/app/serve.go

I had a typo in fuclio serve -ca flag and spent hours trying to work
out why the CA backend was failing. The mispelt flag was being
captured in the middleware handler instead (ca.go line 65) with the
`genericCAError` from errors.go.
This will capture it before the server even starts and make it a
lot easier to see it's just a simple typo.

Validate its a recognised CA

---

cmd/app/serve.go

Signed-off-by: Thomas Runyon <runyontr@gmail.com>
Before the change the logic would fail:
```
go run main.go serve --ca googleca --gcp_private_ca_parent=projects/runyontr/locations/us-east1/ca/fulcio
2021-07-19T15:44:31.130-0400    INFO    app/serve.go:41 booya
2021-07-19T15:44:31.130-0400    FATAL   app/serve.go:42 unknown CA: googleca
github.com/sigstore/fulcio/cmd/app.glob..func2
/Users/tom/go/src/github.com/runyontr/platform-one/big-bang/scratch/sigstore/fulcio/cmd/app/serve.go:42
github.com/spf13/cobra.(*Command).execute
/Users/tom/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860
github.com/spf13/cobra.(*Command).ExecuteC
/Users/tom/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute …
```

change or to and for known CA types

---

pkg/client/client.go

This function has been duplicated in sigstore/cosign and sigstore/sigstore, going to consolidate it here. I'll be adding more common utilities here as I find them. Might consider creating a wrapper class to offer a high-level API over the generated client
Signed-off-by: Jake Sanders <jsand@google.com>

add `pkg/client` for (non-generated) client-related utilities

---

cmd/app/createca.go

There was an issue with invalid key types when verifying
cosign signed registry sigs with a fulcio cert generated using
the fuclio createca command
This PR makes the resulting createca generated cert have partity
to GCA generated certs
The result is a HSM / createca root cert can be used to both sign
and verify registry entries
Resolves: #150

Amend HSM cert usage

---

.github/workflows/verify.yml
config/fulcio-config.yaml
federation/README.md
federation/accounts.google.com/config.yaml
federation/external/oidc.dlorenc.dev/config.yaml
federation/main.go
federation/oauth2.sigstore.dev/config.yaml
go.mod

Script and process to generate OIDC config from federation directory.

---

Makefile
cmd/app/version.go
go.mod

Add a version command for fulcio similar we have for rekor-server

fulcio: add version command

---

Makefile
pkg/generated/client/operations/signing_cert_responses.go

This used to happen in sigstore/sigstore, but was removed in https://github.com/sigstore/sigstore/pull/103. Adding it back in here so that we can include the SCT in the client responses.
needed for https://github.com/sigstore/cosign/issues/591!
Signed-off-by: Priya Wadhwa <priyawadhwa@google.com>

Generate client code with swagger in Makefile

---

pkg/api/ca.go
pkg/api/googleca_signing_cert.go
pkg/ca/googleca/googleca.go
pkg/challenges/challenges.go
pkg/config/config.go

This adds support for handing Github's OIDC tokens in addition to Google and SPIFFE.
Github OIDC tokens look something like:
```json
{
"jti": "0687e989-80d6-42b0-a498-c65e99315f37",
"sub": "repo:mattmoor/stupid-example:ref:refs/heads/main",
"aud": "sigstore",
"ref_protected": "false",
"job_workflow_ref": "mattmoor/stupid-example/.github/workflows/my-action.yaml@refs/heads/main",
"iss": "https://vstoken.actions.githubusercontent.com",
"nbf": 1631210221,
"exp": 1631211121,
"iat": 1631210821
}
```
This change verifies things against the `iss` endpoint, and encodes the
`job_workflow_ref` into the x509 cert as a URI by prefixing it as:
```
https://github.com/{job_workflow_ref}
```
With the example:
```
https://github.com/mattmoor/stupid-example/.github/workflows/my-action.yaml@refs/heads/main …
```

Add support for Github OIDC

---

pkg/ca/fulcioca/fulcioca.go

Fixes: https://github.com/sigstore/fulcio/issues/183
Signed-off-by: Matt Moore <mattomata@gmail.com>

Add Github to `fulcioca` path.

---

cmd/app/createca.go
cmd/app/root.go
pkg/pkcs11/pkcs11.go

Allow to change crypto11.conf file location via `--pkcs11-config-path` command-line parameter
No ticket
```release-note
* add pkcs11-config-path command line parameter to be able to change crypto11.conf file location
```

add pkcs11-config-path command line parameter

---

config/fulcio-config.yaml
federation/external/allow.pub/config.yaml

Add support for fulcio to allow spiffe tokens signed by allow.pub
I'm building an OCI registry that would like to perform server side
cosign support via fulcio. The OCI registry is called vcr.pub and should
be available in beta form soon.
The reason that the domain used here is allow.pub rather than vcr.pub is
one of the future services we'd like to support is other OIDC related
authentication tasks, so we've separated it from the OCI registry off
the bat.

Add support for recoginizing allow.pub as an spiffe issuer

---

.github/workflows/verify-k8s.yml

Fix the incorrect sed substitution lowering the resource requirements. Sed was setting the cpu->memory (again).
Fixes
```release-note
```

fix cutpaste error, sets cpu correctly

---

config/config.jsn
pkg/ca/googlecabeta/googleca.go
pkg/ca/x509ca/x509ca.go
pkg/challenges/challenges.go

Signed-off-by: Asra Ali <asraa@google.com>
draft for https://github.com/sigstore/fulcio/issues/208
* Adds commit sha and trigger (event_name) associated with the github workflow in OID extensions 1.3.6.1.4.1.57264.1.(2/3). 
* Tested this with a id token I grabbed from a workflow, see below: (trigger workflow_dispatch)
```
Certificate:
Data:
Version: 3 (0x2)
Serial Number:
b5:ca:cd:df:e0:98:eb:38:80:f0:40:f6:97:bc:3d:49:93:b0:04
Signature Algorithm: ecdsa-with-SHA384
Issuer: O = sigstore.dev, CN = sigstore
Validity
Not Before: Nov  3 15:33:38 2021 GMT
Not After : Nov  3 15:53:37 2021 GMT
Subject: 
Subject Public Key Info:
Public Key Algorithm: id-ecPublicKey
Public-Key: (256 bit)
pub:
04:af:5a:ee:69:1e:e4:d3:03:b1:0c:c9:8c:f0:12:
04:0f:62:75:36:d7:f9:c0:7e:a4:bb:b2:57:64:03: …
```

Add commit sha and trigger to github workflow

---

cmd/app/createca.go

Looked to me like the descriptions for the flags for street-address and postal-code were cut&paste from locality so changed them.
Fixes
```release-note
```

Fix street-address and postal-code descriptions to be more descriptive.

---

Dockerfile

Signed-off-by: Tuan Anh Tran <me@tuananh.org>
go install `delve` will complain missing version when directory not in module (in Dockerfile) so we will include the `@latest` version when install.
```
go install: version is required when current directory is not in a module
```
Fixes
```release-note
```

fix: go install complain missing version when dir not in module

---

.ko.yaml
cmd/app/createca.go
config/DEVELOPMENT.md
pkg/ca/x509ca/common.go
pkg/ca/x509ca/x509ca.go
pkg/ca/x509ca/x509canocgo.go
pkg/ca/x509ca/x509capurego.go

If specifying golang env `CGO_ENABLED=0`, remove the code that uses PKCS11, because it depends on C. By default, nothing changes, this is just purely an option you must specify.
Fixes #240 
```release-note
* Make it possible to build the binary in pure go mode by specifying `CGO_ENABLED=0`. Because pkcs11 support requires C support, when specifying this option, it does remove the support for `createca` command.
* Fixes #240 
```

plumb through !cgo golang tags that removes pkcs11 support

---

Makefile
cmd/app/root.go
cmd/app/serve.go
main.go
pkg/api/ca.go
pkg/challenges/challenges.go
pkg/config/config.go
pkg/config/config_test.go
pkg/generated/restapi/configure_fulcio_server.go

Thread `FulcioConfig` through to handlers via `ctx` based on a value that's explicitly `Load()`ed at application start.  This is the first of what I expect will be a bunch of refactoring PRs for Fulcio, but I'm trying to take them in bite-sized chunks.  This change:
1. Plumbs through `ctx` as a way we can pass configuration downstream to handlers (here with `FulcioConfig`, but I'd like to kill the usage of `viper` in our library code)
2. Enables us to start reloading `FulcioConfig` (and eventually others!) periodically (or even via an informer!) to avoid needing to cycle pods to force config reloads.
There are some other auxiliary benefits to passing `ctx` like enabling us to model the K8s lifecycle properly by "draining" pods on `SIGTERM`, which I'm not sure we properly handle today …

Thread `FulcioConfig` through from main via `ctx`

---

cmd/app/serve.go
pkg/api/ca.go
pkg/ca/googleca/v1/googleca.go
pkg/ca/googleca/v1beta1/googleca.go
pkg/ca/x509ca/x509ca.go
pkg/config/config.go
pkg/config/config_test.go
pkg/pkcs11/pkcs11.go

Using `viper` (like flags, logging) insider of libraries is a bit of a code smell, so I started to look at where we were using viper directly, and started threading particular bits of configuration through as params, which seems to be the most natural way to do this in most contexts.
Right now there is still a big wad of usage in `pkg/ca/ca.go` (almost entirely in `CA()`), which I'm going to start looking into next, but at least the remainder have been eliminated. 💥 
N/A
```release-note
NONE
```

Consolidate `viper` usage in `pkg/ca/ca.go`

---

cmd/app/serve.go
pkg/api/ca.go

This change builds on https://github.com/sigstore/fulcio/pull/255.  It moves the CA creating to the `serve` entrypoint, and attaches the appropriate `CertificateAuthority` to the request contexts.  The same for the `ct-log-url`.
With this change, all of the `viper` logic lives under `./cmd` and the logic in `./pkg` receives its configurations through parameters (possible attached to `ctx`).
WIP until the base change lands.
N/A
```release-note
NONE
```

Remove `viper` from `pkg/`.

---

cmd/app/serve.go
pkg/ca/googleca/v1/googleca.go
pkg/ca/googleca/v1beta1/googleca.go

This threads `cmd.Context()` into the constructor, and has it call the client constructor directly.  Previously the caller was already wrapped in a `sync.Once`, but not this is all called once from the command's `Run` method.
WIP until https://github.com/sigstore/fulcio/pull/257 merges.
N/A
```release-note
NONE
```

Drop gratuitous `sync.Once` in google CAs.

---

pkg/ca/ephemeralca/ephemeral.go
pkg/ca/googleca/v1/googleca.go
pkg/ca/googleca/v1beta1/googleca.go
pkg/ca/x509ca/common.go

Today we have three copies of Certificate synthesis across:
- x509
- google v1
- google v1beta1
This has burned us several times in recent memory (off the top of my head):
- When I added Github support and missed the x509 path
- When Scott added google v1 and dropped the K8s stuff.
By having a largely common code path for these, we should be able to avoid some of these breaks.
This change creates a method in x509ca to make an `x509.Certificate` and then reorients the bulk of the redundant certificate construction into translation logic from the shared construction.
```release-note
NONE
```

Consolidate the source-of-truth.

---

.github/workflows/verify-k8s.yml

Use the released version of cosign as per todo.
Fixes
```release-note
```

While working on #267 noticed this, but didn't want to bake into it.

---

.gitignore
pkg/api/client.go
pkg/api/options_test.go

Adds a client request timeout option. This closes #266. 
Also adds vim swap files to the gitignore. Can drop this if folks think its not relevant to the PR or repository.
```release-note
* Added `WithTimeout` client option to configure request timeout
```

Make client request timeout configurable with `WithTimeout` client option

---

cmd/app/createca.go
cmd/app/root.go
cmd/app/serve.go
cmd/app/version.go

Makes CLI usage a little more clear by moving global flags to their relevant subcommands. 
**Before**
```bash
$ fulcio createca -h
Create an x509 root CA within a pkcs11 device using values
such as organization, country etc. This can then be used as the root
certificate authority for an instance of sigstore fulcio
Usage:
fulcio createca [flags]
Flags:
--country string          Country name for root CA
-h, --help                    help for createca
--hsm string              The HSM provider to use. Valid values: softhsm (default), aws (default "softhsm")
--locality string         Locality name for root CA
--org string              Organization name for root CA (default "Fulcio Root CA")
--out string              output root CA to file
--postal-code string      Postal code for root CA …
```

Localize flags to each subcommand

---

pkg/ca/x509ca/x509ca.go

When Fulcio is using pkcs11, it expects a private key under the
"PKCS11CA" label. If there is no such key, Fulcio starts successfully
but fails on the first signing request. A much better behavior is to
fail fast and inform the user that the private key is not found upon
start.
Closes: #284

Fail fast if private key is not found when using PKCS11 CA

---

README.md

Just some readme cleanup
```release-note
NONE
```

Update readme for V1 CA Service

---

go.mod
pkg/api/ca.go
pkg/ca/googleca/v1/googleca.go
pkg/ca/googleca/v1beta1/googleca.go
pkg/ca/interface.go
pkg/ca/x509ca/common.go
pkg/ca/x509ca/x509ca.go

This will make the ephemeral and HSM-based CAs easier to use, in addition
to giving us an API to retrieve the existing root cert. This isn't available
in-band today.
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
Fixes
```release-note
```

Add a Root Cert method to the CA interface, and implement it.

---

pkg/api/api_test.go
pkg/api/ca.go
pkg/api/client.go

* Add tests for exercising STL
* Fix #289
* Validates that the new STL tests failed unless backporting #288
Fixes
```release-note
API Additions: Add RootCert method into the pkg/api/client
```

Add RootCert method to client + tests

---

pkg/api/ca.go

I don't actually know what's correct here - but the current client expects
it to be base64 encoded. We could keep it "raw", but then we have to fix the client
that's currently in cosign.
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
Fixes
```release-note
```

Fix the SCT header return value from the API to base64 encode it.

---

pkg/ca/googleca/v1/googleca.go
pkg/ca/googleca/v1beta1/googleca.go

This occurs when authentication is not properly set up. Otherwise,
the service crashes with a nil pointer dereference.

Handle error when there are no roots returned by CA Service

---

docker-compose.yml

I've been working through issues with docker-compose. This is one of the simpler ones to resolve, which is changing the ports so that we can run both Rekor and Fulcio locally at the same time.
Other issues are plumbing through the GCP CA Service CA resource path without having to change the yaml, and there is an issue spinning up a local Dex service.

Change ports for docker compose to avoid conflict with Rekor

---

.github/workflows/verify-k8s.yml
cmd/app/serve.go
config/deployment.yaml
config/fulcio-config.yaml

Modify the viper settings in the serve subcommand to allow users to provide a config file using -c/--config vs. setting everything using command line flags.
Sinc this is based upon viper, the following config file extensions are supported: "json", "toml", "yaml", "yml", "properties", "props", "prop", "hcl", "tfvars", "dotenv", "env", and "ini".
This change also allows using env vars prefixed with FULCIO_SERVE to provide configuration settings as well.
Resolves #314

Enable server settings via config file and env vars

---

OID_INFO.md
pkg/ca/x509ca/common.go
pkg/challenges/challenges.go

With reusable github-workflows the "job_workflow_ref" will reference the shared workflow instead the actual calling workflow.
This adds the additional infos `repository`, `workflow` and `ref` from the Github-Workflow OIDC token as described in #305. According to the [Github-Docs](https://docs.github.com/en/enterprise-cloud@latest/actions/deployment/security-hardening-your-deployments/using-openid-connect-with-reusable-workflows#how-the-token-works-with-reusable-workflows) I added the `repository` field instead of the `repo`.
Fixes #305
```release-note
job_workflow_ref info was insufficient when using with shared github-workflows
```

Extract additional claims from github-workflow token

---

tools/loadtest/README.md
tools/loadtest/locustfile.py
tools/loadtest/requirements.txt

This adds the Locust file used to run a load test against Fulcio.
```release-note
* Added tooling to run load tests against Fulcio
```

Add Locust load test and README

---

docker-compose.yml

There was some change in the last year to use a non-root
user for the Dex image. This causes permission issues
when mounting files, since the non-root user cannot
access the mount. The workaround is to run as root,
which should be fine for development.
See https://github.com/dexidp/dex/issues/1649

Fix docker-compose dexidp startup

---

.github/workflows/validate-release.yml
.github/workflows/verify-k8s.yml
.goreleaser.yml
.ko.yaml
Makefile
release/README.md
release/cloudbuild.yaml
release/release-cosign.pub
release/release.mk

- similar we do for rekor and cosing this PR adds the release makefile rules to build/release fulcio using GCP Cloudbuild and goreleaser
this also generate the multi arch binaries and images for linux and generate the SBOM using syft together with signing using cosign
- https://github.com/cpanato/fulcio/releases/tag/v99.99.99
```console
$ crane manifest gcr.io/cpanato-general/fulcio:v99.99.99                                                                                                                                                                                                                                                                                                                                                                           [68/1418]
{
"schemaVersion": 2, …
```

release: add cloudbuild to run the release for fulcio

---

.github/workflows/codeql-analysis.yml
.github/workflows/main.yml
.github/workflows/verify-k8s.yml
.github/workflows/verify.yml
Dockerfile
Dockerfile.ctfe_init

Addressing https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
data from running `scorecard --show-details --repo=https://github.com/sigstore/fulcio/ --checks Pinned-Dependencies --format json`:
```
{
"date": "2022-01-12",
"repo": {
"name": "github.com/sigstore/fulcio",
"commit": "d890471d80472171effea2ce5a77941d351d2bbe"
},
"scorecard": {
"version": "61a0124",
"commit": "61a01244078b61abf5a2cdced8961927661edb8c"
},
"score": 2,
"checks": [
{
"details": [
"Warn: GitHub-owned action not pinned by hash: .github/workflows/codeql-analysis.yml:38",
"Warn: GitHub-owned action not pinned by hash: .github/workflows/codeql-analysis.yml:42",
"Warn: GitHub-owned action not pinned by hash: .github/workflows/codeql-analysis.yml:46",
"Warn: GitHub-owned action not pinned by …
```

pin github actions by digest instead of tag

---

cmd/app/serve.go
pkg/api/max_bytes.go
pkg/api/max_bytes_test.go

Fixes the the max request body size to 4MiB (Just a guess at a size.... may it could be smaller?) so that it isn't unbound. Implemented using a new `api.WithMaxBytes` middleware. There is a small refactor of how we wire up stuff for the API server here as well to make it a little easier to understand. As adding the body limiting middleware was part of that wire up it seemed a good thing to clean up with this work.
Fixes #335 
```release-note
* Set max request size to 4MiB so that request size isn't unbound
```

Set max request size to 4MiB

---

cmd/app/serve.go

Adds a 1 minute hard coded read, header read, write and idle timeout. This helps prevents accidental or malicious connection exhaustion of the API server.
_Implementation note_
While simply setting `ReadTimeout` would have set the header read and write timeouts to the same value, I think setting them explicitly helps inform the future code readers about the server behaviour in case they're unfamiliar with the behaviour of `http.Server` timeouts.
Fixes #336
```release-note
* Added 1 minute read, write and idle timeouts to API server
```

Add some reasonable timeouts to API server

---

pkg/api/api_test.go
pkg/api/ca.go
pkg/ca/fileca/fileca.go
pkg/ca/interface.go
pkg/ca/x509ca/common.go

The certificate's chain was not being included when issuing
certificates for non-GCP CAs.
We were also adding too many newlines between PEM-encoded
certificates. pem.Encode automatically adds newlines. Just
in case the source that's providing the certificates is
not including trailing newlines, I've added a check to
optionally append newlines. The `dev.sigstore.cosign/chain`
annotation will no longer start with a newline after this change.
I've tested these changes with a local instance of Fulcio, and
there were no issues with Cosign signing and verifying.
Fixes
```release-note
```

Add chain in response for all CAs, fix newlines in response

---

go.mod
go.sum
pkg/ca/x509ca/common.go

This uses the new method in sigstore/sigstore to
generate SKIDs using the cert's public key. Also
updates go.mod/go.sum to use the latest sigstore
release.
Fixes
```release-note
* Generated subject key ID based on certificate public key for non-GCP issued certificates 
```

Generate subject key ID correctly for non-GCP certs

---

cmd/app/createca.go

While following https://github.com/lukehinds/sigstore-the-hard-way - I managed to trigger a panic by running:
`go run . createca --org=acme --country=USA --locality=Anytown --province=AnyPlace --postal-code=ABCDEF --street-address=123 Main St --hsm-caroot-id 0 --out fulcio-root.pem`
which resulted in the following output:
```shell
INFO	app/createca.go:77	binding to PKCS11 HSM
INFO	app/createca.go:97	finding slot for private key: PKCS11CA
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1222616]
goroutine 1 [running]:
github.com/sigstore/fulcio/cmd/app.runCreateCACmd(0xc0001fb680, {0xc0000a6a80, 0x2, 0xc})
/home/t/src/fulcio.up/cmd/app/createca.go:103 +0x616 …
```

createca: Address panic when no private key pair matches

---

cmd/app/serve.go
pkg/api/api_test.go
pkg/api/ca.go
pkg/api/error.go

This work initializes the CT log client once and uses it for all requests instead of making a new one each time.
**Thoughts for reviewers**
The implementation here breaks from our current pattern of injecting dependencies by stuffing them into the request context. I think that explicit dependency inject makes it easier to reason about and test the code. This looks like explicitly asking for the API dependencies on construction and saving them in a struct so they can be accessed like that instead of pulling them out of the request context.
If ya'll agree that this pattern is more clear, I'm happy to iterate and do the same for the other API dependencies like the certificate authority backend and perhaps the logger. If not I'm happy to close this PR and fix using the context stuffing method …

Initialize CT log client once

---

cmd/app/serve.go

Signed-off-by: Thomas Stromberg <t+github@chainguard.dev>
This PR improves the error message when an invalid `--ca` is provided by making it directly actionable. This lowers the friction for folks like me who are blindly pasting lines from the sigstore-the-hard-way doc. 
When I first saw the error message, it did not occur to me that it referenced the `--ca` value versus an expected value within the key pair. Here is the example command-line to trigger the condition:
`fulcio serve --config-path=fulcio-config.json --ca=fulcioca --hsm-caroot-id=1 --ct-log-url=http://localhost:6105/sigstore --host=0.0.0.0 --port=5000`
**Old output**
`FATAL	app/serve.go:119	unknown CA: fulcioca`
**New output**
`FATAL	app/serve.go:119	--ca=fulcioca is not a valid selection. Try: pkcs11ca, googleca, fileca, or …

Make the the invalid CA error message actionable

---

cmd/app/serve.go
pkg/config/config.go

Signed-off-by: Thomas Stromberg <t+github@chainguard.dev>
This PR improves the error message output when the OIDC Issuer URL is not valid. For example, with this command-line: `fulcio serve --ca=pkcs11ca --hsm-caroot-id=1 --ct-log-url=http://localhost:6105/sigstore --host=0.0.0.0 --port=5000`
`FATAL	app/serve.go:130	error loading config: 404 Not Found: 404 page not found`
`FATAL	app/serve.go:131	error loading --config-path=/etc/fulcio-config/config.json: provider http://localhost:5556/auth: 404 Not Found: 404 page not found`
```release-note
NONE
```

Improve error message when an invalid OIDC issuer is provided

---

cmd/app/serve.go
pkg/api/api_test.go
pkg/api/ca.go

Small refactor to make the CA an explicit dependency of the API handler instead of stuffing it in the request context
```release-note
NONE
```

Make CA explicit dependency of API handler

---

pkg/api/ca.go

Signed-off-by: Thomas Stromberg <t+github@stromberg.org>
Addresses a panic caused by the incorrect string being referred for a newline check.
This panic only occurs if finalPEM is shorter than finalChainPEM.
Fixes #369
```release-note
NONE
```

Address signingCert panic with the last-byte calculation of finalChainPEM

---

go.mod
go.sum

Signed-off-by: Thomas Stromberg <t+github@chainguard.dev>
Currently, the fulcio does not build on OpenBSD:
```
$ go test .
ld: error: unable to find library -ldl
```
This PR upgrades the miekg/pkcs11 library to a version that compiles cleanly on OpenBSD. Here are the functional PR's included in the miekg/pkcs11 upgrade from v1.0.3:
* https://github.com/miekg/pkcs11/pull/124
* https://github.com/miekg/pkcs11/pull/133
* https://github.com/miekg/pkcs11/pull/137
* https://github.com/miekg/pkcs11/pull/140
* https://github.com/miekg/pkcs11/pull/143
* https://github.com/miekg/pkcs11/pull/150
For a more specific diff, see https://github.com/miekg/pkcs11/compare/v1.0.3...v1.1.1
NOTE: This PR was created using `go get github.com/miekg/pkcs11@v1.1.1`.
Fixes #375
```release-note
miekg/pkcs11 …
```

Upgrade miekg/pkcs11 library from v1.0.3 to v1.1.1

---

cmd/app/serve.go
pkg/api/ca.go
pkg/ctl/client.go
pkg/ctl/client_test.go
pkg/ctl/ctl_logging.go
pkg/ctl/ctl_logging_test.go
pkg/ctl/errorresponse.go
pkg/ctl/interface.go
pkg/ctl/logging.go

In an attempt to de-cluster the all powerful `api.(*api).signingCert` method, I've moved to logging logic for the CT log client over into the CT log package. This is achieved by
- Abstracting the CTL client into an interface
- Creating a `ctl.WithLogging(inner ctl.Client, logger *Logger) ctl.Client` middleware to instrument the client
- Finally removing the logging from the `signingCert` method
```release-note
NONE
```

Move CTL logging logic over to CTL package

---

pkg/api/ca.go
pkg/api/ca_test.go

Fixes a compatibility issue where content-type "application/json; charset=UTF-8" wasn't allowed.

Allow parameterized application/json content types

---

pkg/api/client.go

Signed-off-by: Thomas Stromberg <t+github@stromberg.org>
This improves error messages returned by SigningCert, specifically adding the URL and status code when an unexpected response code occurs. Currently, if one accidentally points the Fulcio client at a non-Fulcio endpoint, the error message isn't very helpful; particularly when an empty HTTP response body is encountered.
`retrieving cert:  `
`retrieving cert: POST http://localhost:5000/api/v1/signingCert returned 403 Forbidden: ""`
Fixes #387
```release-note
NONE
```

Improve error messages returned by SigningCert

---

pkg/ca/googleca/v1/googleca.go
pkg/ca/googleca/v1/googleca_test.go

The fields of the Subject proto do not need to be
specified, but the Subject proto is still required.
This does result in an empty subject when viewing
the certificate in openssl or macOS keychain, but
this is something I'll be filing an issue with CAS for.
Tested by running a local instance of Fulcio with
my own instance of CA Service.
Fixes #390
Fixes #390 
```release-note
Removed organization from GCP CA Service issued certificates
```

Remove organization from subject for GCP CAS issuer

---

cmd/app/serve.go
go.mod
go.sum
pkg/api/metrics.go

Part of monitoring for GA! We can count, track and start alerting if error codes start to increase.
Seems like we only have one endpoint at the moment, but it would be nice if that was including in these metrics later on!

Count HTTP request error codes with prometheus

---

DEPRECATIONS.md
FEATURES.md

Adding deprecation policy and feature stability docs based on the policy described [here](https://docs.sigstore.dev/api-stability). I guessed at the most important features to include, but let me know if I'm missing anything!
I put everything in `beta` right now because Fulcio isn't 1.0, but happy to move features to other sections if that's more accurate.
Ref https://github.com/sigstore/sigstore-website/issues/119

Add feature stability and deprecation docs

---

pkg/oauthflow/oidc_test.go

Signed-off-by: Elizabeth Thomas <email2eliza@gmail.com>
Adding unit tests for EmailFromIDToken method in oauthflow.oidc
Fixes https://github.com/sigstore/fulcio/issues/405
```release-note
```

Add unit tests for oidc-EmailFromIDToken method

---

README.md
docs/developer.md

Part of https://github.com/sigstore/fulcio/issues/372
This PR extract the part related to building fulcio for development from README to it's own file in docs/ folder.
/cc @nsmith5

Extract development documentation from README

---

.github/workflows/cut-release.yml
hack/github-oidc-setup.sh
release/README.md

Create a Github Actions Workflow that will mostly automate the cutting of a release
- draft a release with specified tag [this uses the gh cli]
- kick off cloud build to create artifacts [this uses gcloud cli]; this will also require the creation of a new service account to leverage the oidc login flow, the commands/script to create the service account is included in the PR.
only inputs needed are 
- release tag
- cosign key ring name
- cosign key name
The last two parameter can be hardcoded or if it is sensitive, stored as a secret and referenced that way. Let me know if this is desirable and I can update the workflow.
To avoid just anyone starting the workflow to create a release, it is hardcoded to allow one of
"bobcallaway","cpanato","dlorenc","lukehinds" to start it.
Anyone else that …

Automate release

---

go.mod

From https://sigstore.slack.com/archives/C02K0T1LNPQ/p1645575739690499: 
> `go test -v ./...` fails on main for me, but I can't tell why this wasn't caught in CI 🤔 
> ```
> $ go test -v ./...
> go: github.com/sigstore/fulcio/pkg/oauthflow: package github.com/magiconair/properties/assert imported from implicitly required module; to add missing requirements, run:
>	go get github.com/magiconair/properties/assert@v1.8.5
>```
> `go mod tidy` indeed generates a diff adding this dependency so I'll open a PR to add this, but I'm curious about why CI isn't having a bad time....
```release-note
NONE
```

Add missing testing dependency

---

.github/workflows/verify-k8s.yml

add indent to fix yaml error

---

.github/workflows/cut-release.yml
Makefile
release/README.md
release/cloudbuild.yaml
release/release.mk

Copy signed released image from GCR to GHCR using cosign cli copy command.
This will ensure the signature will be the same between the two registry.
@cpanato I had to plumb a new GITHUB_USER env var to allow docker auth to copy image from GCR to GHCR. Not sure if there is a better way or not. Please take a look.
Fixes #421 
```release-note
Signed release images will now be available in GitHub Container Registry
```

Mirror signed release images from GCR to GHCR as part of release with Cloud Build.

---

.github/workflows/main.yml

This adds codecov as the code coverage tool for PRs.
Similar to what is being done in rekor in https://github.com/sigstore/rekor/pull/676
Resurrecting #430 @nsmith5 
Fixes
```release-note
None
```

Add codecov as github action.

---

release/release.mk

- while doing some tests notice the sed is kind of broken and also update the var to use the git tag, which I guess was the initial idea
update the sed to make it work
the error
```
Step #3: sed -i -e 's;gcr.io/projectsigstore/fulcio:.*;gcr.io/projectsigstore/fulcio:2f2561a0c752aa4c4cafe14dcdb95b4911b01ff8/g' fulcio-v0.2.0.yaml
Step #3: sed: -e expression #1, char 107: unterminated `s' command
```
after the change and using my docker registry as a name
```
....
- name: fulcio-server
image: ctadeu/fulcio:v0.2.0-1-g2bc6c5a-dirty
ports:
....
```
n/a
```release-note
NONE
```

release: fix sed to update the manifests

---

docs/oidc.md

This outlines what is required for each OIDC issuer and how the
OIDC claims are used in the issued certificates.
`username` and `uri` flows are under review - https://github.com/sigstore/fulcio/pull/455 and https://github.com/sigstore/fulcio/pull/463
Fixes
```release-note
```

Add documentation for OIDC configuration and tokens

---

.github/workflows/cut-release.yml
.goreleaser.yml
release/cloudbuild.yaml
release/release.mk

- the sed was missing to parse the KO_PREFIX env var brackets so that fail as well
```
Step #3: sha256:5f67c995503680f34105fae4d825c057dbed16056ceabc4926de2c3ab82574ef
Step #3: sed -i -e 's/gcr.io/projectsigstore\/fulcio@.*/gcr.io/projectsigstore\/fulcio:v0.2.0/g' fulcio-v0.2.0.yaml
Step #3: sed: -e expression #1, char 38: unknown option to `s'
```
- update the github user to the bot, which is the token key we use in cloudbuild
- remove duplicate step in cloudbuild
- update image to do the image copy to have cosign
rehearsal using this change https://github.com/cpanato/fulcio/releases/tag/v99.99.02
n/a
```release-note
NONE
```

fix sed and update job

---

.github/workflows/cut-release.yml

Leverage the reusable Release workflow in sigstore/sigstore repo so releases will be cut in the same manner across Cosign|Rekor|Fulcio.
The reusable workflow is pending review in https://github.com/sigstore/sigstore/pull/325
Fixes
Works toward fixing https://github.com/sigstore/public-good-instance/issues/50
```release-note
```

Use reusuable release workflow in sigstore/sigstore

---

pkg/api/api_test.go
pkg/challenges/challenges.go
pkg/challenges/challenges_test.go

Fixes #398
```release-note
Added OIDC issuer type for username subjects
```

Update Username OIDC flow based on comments 

---

Makefile

- fix build date format for version command
xref: https://github.com/sigstore/cosign/pull/1644
n/a
```release-note
NONE
```

fix build date format for version command

---

docs/security-model.md

Minor typos.
Signed-off-by: John Speed Meyers <jsmeyers@chainguard.dev>

Fix minor typos in security model README

---

docs/how-certificate-issuing-works.md

Minor typos in docs. Will fix DCO if dorked up. 🤞 
Signed-off-by: John Speed Meyers <jsmeyers@chainguard.dev>

Fix certificate README typos

---

pkg/ca/fileca/fileca.go

Add missing reader lock to File CA when reading certificate chain

---

pkg/ca/fileca/fileca.go

The last fix guarded against writes, but as pointed out in another PR,
the set of certificates could change between fetching the cert/key pair,
and using the cert chain in the response. The fix simply reads the cert
chain and private key once.
Fixes
```release-note
```

Fix concurrency properly in File CA implementation

---

pkg/api/client.go

Signed-off-by: Jason Hall <jasonhall@redhat.com>
Fixes #501 
```release-note
Client request to fetch root cert honors provided timeout and useragent
```
@vaikas

Use provided HTTP client instead when fetching root cert

---

cmd/app/createca.go
go.mod
go.sum
pkg/ca/ephemeralca/ephemeral.go
pkg/ca/x509ca/common.go
pkg/ca/x509ca/common_test.go

UUIDs generate 16 byte serial numbers. Serial numbers can be no larger
than 20 bytes. They also must be positive, giving us 159 bits to
generate a serial number.
This does not affect prod currently, since CA Service generates its own serial numbers. This will affect prod once we switch to using an intermediate CA.
Fixes
```release-note
Generate 20 byte positive serial numbers for certificates
```

Generate larger, compliant serial numbers

---

CHANGELOG.md

- add changelog for v0.3.0 release
n/a
```release-note
add changelog for v0.3.0 release
```

add changelog for v0.3.0 release

---

docs/ctlog.md

Includes information about embedded SCTs and the log
sharding strategy.
Fixes #510, #43
```release-note
```

Add documentation for CT log

---

examples/README.md
examples/request-certificate/main.go
go.sum

The API isn't super clearly documented and the workflow how to fetch certificates is not well explained. There are no simple code examples nor examples around that makes fulcio easy to pick up. This is a start at providing examples for how to utilize fulcio  and something we should look at adopting for the other sigstore projects as well.
Signed-off-by: Morten Linderud <morten@linderud.pw>

examples: This adds example code on how to fetch a fulcio certificate

---

cmd/app/serve.go
config/logid.sh

This is an optional flag to verify an SCT before returning it to the
client.
Fixes
```release-note
```

Read public key of CT log from path to verify SCTs

---

pkg/api/grpc_server_test.go
pkg/ca/x509ca/common.go

The key usage should be Digital Signature, not Key Cert Sign. The latter
requires that isCA also be asserted. The certificate's key is only used
to verify signatures, not certificates.
Note that this does not affect the GCP CA.
Fixes #550
```release-note
Fixed key usage for issued certificates not from GCP CA Service
```

Fix key usage for issued certificates

---

fulcio.proto
fulcio_legacy.proto

Small doc clarification about the legacy HTTP API.
No ticket, but this came up in the 2022-04-19 community meeting.
```release-note
NONE
```

Add note about the status of the legacy HTTP API.

---

CHANGELOG.md

- add changelog for 0.4.1 release
n/a
```release-note
NONE
```

add changelog for 0.4.1 release

---

pkg/identity/issuer.go
pkg/identity/issuerpool.go
pkg/identity/issuerpool_test.go
pkg/identity/principal.go

Adds identity package with `Issuer` and `Principal` abstractions as well as an `IssuerPool` implementation that matches a token against a pool is issuers to authenticate. This work is part of a larger refactor of our identity issuer code as described [here](https://docs.google.com/document/d/1PKAou7wEmEob4VOLq6rFlx5maOM5hkJ3XffZizfwdFw/edit). 
Future work includes:
Partially addresses #275 along with the other future works describe above
```release-note
NONE
```

Add new `Issuer` and `Principal` abstractions

---

pkg/config/config.go

Limit HTTP requests to OIDC discovery endpoints to 10 seconds before
cancelling and returning an error
Fixes #511 
```release-note
* Limited OIDC discovery requests to 10 seconds before timing out
```

Add timeout to OIDC discovery

---

pkg/ca/x509ca/common.go
pkg/ca/x509ca/common_test.go
pkg/ca/x509ca/extensions.go
pkg/ca/x509ca/extensions_test.go

Adds a new extensions structure that documents the global set of
extensions added to our certificates and a method to render that data
into extensions.
Related to #275 
```release-note
* NONE
```

Refactor x509 extension embedding logic

---

pkg/api/client_test.go

Adds some tests for the `WithTimeout` and `WithUserAgent` options for the client. While this legacy client will be deprecated soon, these were some easy tests to write so why not? Not sure if we're keeping library API compat in the deprecation to GRPC, but if so perhaps these can be good tests to make sure we reimplement this when cutting over to the new client.
```release-note
NONE
```

Add client options testing

---

pkg/ca/googleca/v1/googleca.go
pkg/ca/interface.go
pkg/ca/intermediateca/intermediateca.go
pkg/ca/intermediateca/intermediateca_test.go
pkg/ca/x509ca/common.go

Removes the `Subject` field from `CodeSigningCertificate` and `CodeSigningPreCertificate` as the field is unused in the rest
of the code base. This change helps to remove the usage of `challenges.ChallengeResult` in general as we move to the newer
identity issuer abstraction.
_Bonus_: Check out that git commit signature! Signed by Fulcio :D
```release-note
NONE
```

Remove unused `Subject` field from `CodeSigningCertificate`

---

pkg/ca/ca.go
pkg/ca/csc.go
pkg/ca/csc_test.go
pkg/ca/cspc.go
pkg/ca/embeddedca.go
pkg/ca/error.go

Slit up the the structs / interfaces in `pkg/ca` into seperate files and add tests for serialization / deserialization methods on `CodeSigningCertificate`
```release-note
NONE
```

Small `ca` refactor

---

pkg/api/grpc_server.go
pkg/challenges/challenges.go
pkg/challenges/challenges_test.go

Use `cryptoutils.ParseCSR` and remove the implementation in pkg/challenges.

challenges: remove ParseCSR

---

pkg/identity/principal.go

Clarifies that Name _must_ match the proof of possession.
@haydentherapper let me know if you can thing of a better name for the method. Happy to add that in here. Thought I'd at least improve the docs while I remembered to.

identity: improve the documentation for Principal.Name()

---

pkg/challenges/challenges_test.go
pkg/oauthflow/oidc.go
pkg/oauthflow/oidc_test.go

Just a smattering of different tests for challenge results. Wanted to increase coverage before migrating into issuer abstraction.

Add some tests for challenges

---

pkg/config/config_network_test.go
pkg/config/config_test.go

The config tests make outbound network calls since Load() calls
prepare() which fetches the OIDC configs. Tests that call Load() will
now be skipped. Tested with `go test -tags=hermetic ./...` without a
network connection.
Fixes #480
```release-note
In hermetic environments, tests that require network access can be skipped with -tags=hermetic
```

Skip tests that require network access with HERMETIC=true

---

pkg/api/error.go
pkg/api/grpc_server.go
pkg/challenges/challenges.go
pkg/challenges/challenges_test.go

The challenge verification logic is sort of mixed up with the OIDC token parsing at the moment. This work makes two changes to this logic to make it a little easier to understand (there is one commit per change so you can read one at a time if desired)
- Break up the OIDC parsing logic and proof of possession verification in `ExtractSubject` into two seperate things
- Group all the logic for verifying a CSR together and all the logic for verify a signed subject proof of possession together. Make a really clear branch in logic between these two completely different challenges.

Refactor challenge verification

---

pkg/api/grpc_server_test.go
pkg/challenges/challenges.go
pkg/challenges/challenges_test.go
pkg/config/config.go
pkg/config/config_test.go

SPIFFE issuers must configure a trust domain. We no longer assume that
the the trust domain has some implicit relationship with the OIDC issuer
domain. Tokens with a mismatch in trust domain are rejected.
```release-note
* SPIFFE issuers must now configure a trust domain and tokens with mismatched trust domains will be rejected
```

Correct SPIFFE trust domain checking

---

config/fulcio-config.yaml
federation/external/allow.pub/config.yaml
federation/external/oidc.dlorenc.dev/config.yaml
federation/main.go
go.mod
go.sum
pkg/challenges/challenges.go
pkg/challenges/challenges_test.go
pkg/config/config.go
pkg/config/config_test.go

This adds extra enforcement that trust domains are valid on startup, and
validates that SPIFFE IDs in tokens are also of a valid format.
Comparison is now done via the library too.
Fixes
```release-note
Stronger validation of SPIFFE IDs and trust domains
```

Validate SPIFFE IDs and trust domains via library

---

cmd/app/http.go
cmd/app/serve.go
cmd/app/version.go
go.mod

cmd/app: remove dependency on deprecated github.com/pkg/errors
Fixes: https://github.com/sigstore/cosign/issues/1880

cmd/app: remove dependency on deprecated github.com/pkg/errors

---

pkg/ca/ephemeralca/ephemeral_test.go
pkg/ca/x509ca/common_test.go
pkg/oauthflow/oidc_test.go

Added additional tests for CA implementations and OIDC

---

pkg/challenges/challenges.go
pkg/config/config.go
pkg/config/config_test.go

Using a claim other than "iss" to set the issuer on a certificate only
makes sense for federating identity issuers like Dex. This restricts the
issuers configued to this setting to email type issuers.
cc @haydentherapper 
```release-note
* Restricted usage of "IssuerClaim" to configure which claim is used to set the issuer extension to email type issuers.
```

Restict issuer claim mapping to email issuers

---

pkg/api/grpc_server_test.go

We were lacking any test coverage for IssuerClaim. This test shows that
the issuer in the issued certificate will come from the claim specified
in IssuerClaim instead of from the issuer claim.
Fixes
```release-note
```

Add e2e test that tests IssuerClaim

---

.golangci.yml
Makefile
cmd/app/grpc.go
cmd/app/http.go
cmd/app/version.go
pkg/server/error.go
pkg/server/grpc_server.go
pkg/server/grpc_server_test.go
pkg/server/legacy_server.go
pkg/server/max_bytes.go
pkg/server/max_bytes_test.go
pkg/server/metrics.go
pkg/server/version.go

Signed-off-by: Miloslav Trmač <mitr@redhat.com>
Split pkg/server from pkg/api
N/A
```release-note
External users of pkg/api that refer to the server code now need to use pkg/server.
```
---
API clients using `pkg/api.NewClient`, like `github.com/sigstore/cosign`, currently end up depending on all the implementation details of the servers, unnecessarily increasing their binary size and supply-chain attack surface.
Instead, move the server code to a new pkg/server (assuming there are no external users of that functionality), and leave pkg/api as a package only providing a client (as it is used in practice, and documented in various places in this repo).
The move includes `pkg/api/version.go`, because it is only useful with a Go build that specifies the various values at build time, which is …

Split pkg/server from pkg/api

---

cmd/app/serve.go

Adds a flag to make the prometheus metrics port configurable and defaults the current hard coded 2112.
When folks run through the popular https://blog.chainguard.dev/sigstore-the-local-way/ they find that Fulcio and Rekor and both hardcoded to use 2112 for prom endpoint and the can't both run on local host without recompiling one or the other. This allows folks to supply a different port.
```release-note
* Made prometheus port configurable
```

Make prometheus port configurable

---

docs/oid-info.md

Signed-off-by: Jason Hall <jason@chainguard.dev>
```release-note
NONE
```

typo: Github -> GitHub

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update cross-builder image to use go1.18.3
n/a
```release-note
NONE
```

update cross-builder image to use go1.18.3

---

pkg/log/log.go

change grpc response logger to debug level instead of error

---

cmd/app/serve.go
pkg/ca/baseca/baseca.go
pkg/ca/baseca/baseca_test.go
pkg/ca/common.go
pkg/ca/common_test.go
pkg/ca/ephemeralca/ephemeral.go
pkg/ca/ephemeralca/ephemeral_test.go
pkg/ca/extensions.go
pkg/ca/extensions_test.go
pkg/ca/fileca/fileca.go
pkg/ca/fileca/load.go
pkg/ca/googleca/v1/googleca.go
pkg/ca/kmsca/kmsca.go
pkg/ca/pkcs11ca/pkcs11ca.go
pkg/ca/pkcs11ca/pkcs11canocgo.go
pkg/ca/x509ca/x509ca.go
pkg/identity/email/principal.go
pkg/identity/github/principal.go
pkg/identity/kubernetes/principal.go
pkg/identity/spiffe/principal.go
pkg/identity/uri/principal.go
pkg/identity/username/principal.go
pkg/server/grpc_server_test.go

There is no difference between the CreateCertificate implementation for x509ca and intermediateca, so I did a few refactors to merge the two implementations:
* Moved intermediateca to baseca package
* Moved extensions.go and common.go out of x509ca, since x509ca is just for pkcs11, and this caused an import cycle
* Refactored x509ca and ephemeralca to embed baseca.BaseCA, removing the duplicate CreateCertificate/Root implementations
* Renamed x509ca to pkcs11ca
* Moved VerifyCertChain to common.go, since it didn't need to be a function of baseca
The primary benefit of this refactor is that all CA implementations that use the base CA implementation will support embedded SCTs. googleca is a special case.
Fixes
```release-note
Refactored ephemeralca and pkcs11ca to support embedded SCTs
```

Refactor in-memory signing CAs to use a single implementation

---

.golangci.yml
cmd/app/serve.go
cmd/create_tink_keyset/create_tink_keyset.go
cmd/fetch_ca_cert/fetch_ca_cert.go
docs/setup.md
go.mod
go.sum
pkg/ca/tinkca/signer.go
pkg/ca/tinkca/signer_test.go
pkg/ca/tinkca/tinkca.go
pkg/ca/tinkca/tinkca_test.go
pkg/test/cert_utils.go

This adds support for using encrypted Tink keysets to load a signer.
There are two main benefits from this work: We can leverage this instead
of KMS if we need to support a higher QPS, and Tink keysets use strong
secure defaults. Keysets can be encrypted with AESGCM, do not rely on a
KDF, cannot be brute-forced, and access to the key can be audited
through cloud audit logs.
Tink does not provide a method to extract the signing key from the
keyset intentionally, so I wrote a helper library to reach into the key
handle proto to construct a crypto.Signer.
Fixes #646
```release-note
Added Tink signing backend for signing certificates with a local encrypted Tink keyset
```

Add Tink signing backend

---

.github/workflows/protoc-dependabot-hack.yml

add dependabot hack to monitor for new protoc releases

---

pkg/log/log.go

Confirmed with `docker logs -f fulcio-server 2>/dev/null`
This only fixes the development logger, not the prod one.
Fixes #641 

pipe all log messages to stdout for dev logger

---

.github/workflows/validate-release.yml

This fixes errors reported in CI due to using back-level cosign.
https://github.com/sigstore/fulcio/runs/7401355413?check_suite_focus=true

bump cosign to v1.9.0

---

docs/oidc.md

No functional changes. Just noticed that these code blocks were missing syntax highlighting while reading the docs.
Signed-off-by: William Woodruff <william@trailofbits.com>

[NFC] docs/oidc: mark code blocks as JSON, minor syntax fixes

---

docs/certificate-specification.md

This outlines what MUST and SHOULD and MAY and SHOULD NOT
and MUST NOT be included with CA and end-entity certificates.
Fixes #698

Create certificate specification

---

cmd/create_tink_keyset/create_tink_keyset.go
cmd/fetch_ca_cert/fetch_ca_cert.go
go.mod
go.sum
pkg/ca/tinkca/tinkca.go

- update github.com/google/tink/go to 1.7.0 and fix deprecation

update github.com/google/tink/go to 1.7.0 and fix deprecation

---

.github/workflows/verify.yml
cmd/app/serve.go

- address Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server
- update golangci-lint to 1.48.0
- address Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server

address Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder and cosign images

update builder and cosign images

---

cmd/app/grpc.go

On MacOS it seems subsequent attempts to bind to the abstract Unix
socket fail without first explicitly removing it. This issue seems to be
MacOS-specific as it doesn't occur on an Ubuntu VM (using `lima`).
Fixes sigstore/fulcio#738
Signed-off-by: Paul Thomson <thomsonp83@gmail.com>

Clean up unix socket

---

release/cloudbuild.yaml

Getting this error while doing the release
```
Step #3:   ⨯ release failed after 4m47s                       error=sign: cosign failed: exit status 1: Using payload from: /workspace/go/src/sigstore/fulcio/dist/fulcio-linux-ppc64le
Step #3: Generating ephemeral keys...
Step #3: Retrieving signed certificate...
Step #3: 
Step #3:         Note that there may be personally identifiable information associated with this signed artifact.
Step #3:         This may include the email address associated with the account with which you authenticate.
Step #3:         This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.
Step #3: Error: signing /workspace/go/src/sigstore/fulcio/dist/fulcio-linux-ppc64le: getting key from …
```

adding tuf root env variable

---

.github/workflows/validate-release.yml
.github/workflows/verify-k8s.yml
.github/workflows/verify.yml
.golangci.yml
Dockerfile
Dockerfile.ctfe_init
federation/main.go
pkg/config/config.go
pkg/config/config_network_test.go
pkg/generated/protobuf/fulcio.pb.go
pkg/generated/protobuf/fulcio_grpc.pb.go
pkg/generated/protobuf/legacy/fulcio_legacy.pb.go
pkg/server/max_bytes_test.go
release/cloudbuild.yaml

upgrade to go1.19

---

Makefile
cmd/app/root.go
cmd/app/version.go
go.mod
go.sum
pkg/server/metrics.go

- export fulcio build/version information
- use the same way to expose version information as we use in rekor and other projects
with this, we can add a dashboard to see what version we have deployed and also can be used to compare between environments which I saw a issue around but was not able to find it
also fixes partially: https://github.com/sigstore/public-good-instance/issues/714
```
fulcio_build_info{build_date="2022-10-07T16:22:46",goversion="go1.19.2",revision="f2f24ac39392e366949a50972c8851bde2d39b7a",version="v0.6.0-9-gf2f24ac"} 1
```

use same way to output version and expose build info to prometheus

---

.github/workflows/main.yml
cmd/app/grpc.go
cmd/app/http_test.go

`grpcServerEndpoint` could be read at any point depending on goroutine scheduling. Sometimes that read occurred (appearing intermittently in CI testing) after memory for a string was allocated but before the string value was populated with non-null bytes, leading to issues as reported in #840. 
This reduces the scope of what is run within the go routine when launching the grpc server.
Fixes: #840

fix race condition in unit tests

---

pkg/ca/googleca/v1/googleca.go

I was playing around with some stuff and realized I needed to pass in some extra options. This just exposes the google options so that folks using this as a library can pass them in. 

Expose client options for google ca

---

pkg/ca/pkcs11ca/pkcs11canocgo.go

Was seeing this bug on my M1 when running `ko build .`, since `PKCS11CA` needs to be redefined for the no-cgo case. The error was:
```
$ ko build .
pkg/ca/pkcs11ca/pkcs11canocgo.go:26:2: undefined: baseca
```
We define `type PKCS11CA struct` for the cgo case here, so this just does the same for the no-cgo case:
https://github.com/sigstore/fulcio/blob/81ecec8bb8bc0cd1f42fc445e48854167f19bc7d/pkg/ca/pkcs11ca/pkcs11ca.go#L39-L41

Fix pkcs11ca with no cgo compilation bug

---

cmd/app/serve.go
pkg/ca/googleca/v1/googleca.go
pkg/ca/googleca/v1/googleca_test.go

This fixes 2 bugs in the googleca:
1. We would always fail in `TrustBundle` because we were checking `if len(roots) == 0` instead of `if len(caCerts) == 0`, roots was always empty at this point
2. Allow specifying certificateAuthority in the `gcp_private_ca_parent ` flag
Fix bugs in googleca and update flag description

Fix bugs in googleca and update flag description

---

pkg/identity/github/principal.go

Nothing major, as its only a comment.
I happened to be looking for the well-known config of github, so searched around in fulcio. Found the one to */githubcontent.com/ , tried to curl and got a redirect to some not very friendly looking site.
This changes it to the correct site.

Incorrect URL points to malicious site (in commented code)

---

cmd/app/serve.go
pkg/ca/kmsca/kmsca.go
pkg/ca/kmsca/kmsca_test.go

Signed-off-by: Hector Fernandez <hector@chainguard.dev>
This PR aims to refactor the KMSCA constructor to accept an array of x509 certificates instead of a file path. This makes this function more reusable, as well as it moves the processing of the viper flags to the cmd pkg.

Refactor kmsca constructor to accept x509.Certificates

---

pkg/ca/kmsca/kmsca.go

I realized I needed to pass in some extra RPC options (e.g. OIDC Auth). This just exposes all the  RPC options so that folks using this as a library can pass them in.

Expose RPC options to set oidc auth creds for KMS

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder release to use go 1.19.5 and refactor validate release job

update builder release to use go 1.19.5 and refactor validate release job

---

config/fulcio-config.yaml
federation/agent.buildkite.com/config.yaml
pkg/challenges/challenges.go
pkg/config/config.go
pkg/config/config_test.go
pkg/identity/buildkite/principal.go
pkg/identity/buildkite/principal_test.go
pkg/server/grpc_server_test.go

Add Buildkite to the OIDC connect federation configuration. Fixes #889.
I'd like to be able to use Buildkite OIDC tokens to sign containers produced by my builds. There are more details in #889.
Our OIDC token support is still under development, but it's possible to try it out now by signing up for Buildkite and running a pipeline like:
```
steps:
- command: |
docker build -t sj26/test:$BUILDKITE_BUILD_NUMBER .
COSIGN_EXPERIMENTAL=1 \
cosign sign \
--identity-token="$$(buildkite-agent oidc request-token --audience sigstore)" \
"sj26/test:$${BUILDKITE_BUILD_NUMBER}"
```
I wasn't sure about the "type", so I followed the example of "github-workflow" — our tokens represent one "buildkite-job" which is a process being run on a host somewhere as part of a build pipeline.
- Add Buildkite OIDC to …

Add Buildkite OIDC to Fulcio

---

config/fulcio-config.yaml
federation/main.go

Closes https://github.com/sigstore/fulcio/issues/970
This adds the newly detected OIDC Issuer URL format for AKS clusters as an additional meta issuer. I added a new one instead of replacing the existing one in case that issuer URL is being used under different circumstances.
* Support the new format of AKS OIDC Issuers
N/A

Add new format for AKS OIDC issuer

---

cmd/app/serve_test.go

The test was failing because the duplex server hasn't started up before a request was made. This adds a brief pause to give a chance for the server to start up.

Fix Duplex test

---

codecov.yml

This will still include the comment from the codecov bot, but will disable patch/project GHAs. Would be nice to add these back at some point.

Disable failing checks for codecov

---

pkg/config/config.go
pkg/config/config_test.go

This will allow us to start setting up custom issuers! Right now this [switch](https://github.com/sigstore/fulcio/blob/main/pkg/config/config.go#L462) statement prevents users from doing that, but allowing the challenge claim to be specified in the Fulcio config should resolve that.

Allow specifying ChallengeClaim for an Issuer in the Fulcio config

---

pkg/identity/authorize.go
pkg/identity/email/issuer.go
pkg/identity/email/issuer_test.go
pkg/identity/github/issuer.go
pkg/identity/github/issuer_test.go
pkg/server/grpc_server.go

I've been working on setting up Fulcio internally and ran into some blockers. I found this TODO in the code:
https://github.com/sigstore/fulcio/blob/13a2378a85f008e47bb445e79dedac1a49f605cf/pkg/server/grpc_server.go#L79-L81
This PR is the first step to completing it! This PR is 1/n in which I'll implement the [Issuer](https://github.com/sigstore/fulcio/blob/main/pkg/identity/issuer.go#L19) interface for each identity type, ultimately switching over to calling the interface functions for authentication. A lot of this work was already done by @nsmith5, I'm just finishing it up. 
The main benefit of this work is that it'll allow users to specify custom Issuers and Issuer Types if needed, making the upstream code more extensible.

Begin implementing Issuer interface for email and github identities

---

pkg/identity/kubernetes/issuer.go
pkg/identity/kubernetes/issuer_test.go
pkg/identity/spiffe/issuer.go
pkg/identity/spiffe/issuer_test.go

Implement Issuer interface for spiffe and kubernetes types

---

pkg/server/issuer_pool.go
pkg/server/issuer_pool_test.go

There's a chance the issuer can be nil if it's a custom issuer. If it's nil, don't add it to the issuer pool.

Don't add nil issuers to issuer pool

---

docs/oidc.md

Add documentation for adding a new OIDC issuer

---

README.md

We now have to use the 5th TUF root. Also added instructions to verifying releases using the artifact public key from the TUF repo. 
Also updated the slack link.

Update TUF instructions in README

---

docs/oid-info.md

It was pointed out that CI providers may not be able to meet the Build Signer Digest requirement if they've been using server-assigned UUIDs to identify CI jobs rather than a user-verifiable digest.
Everyone seems to be in agreement that this is something CI providers SHOULD strive for so that users have a means of detecting misbehavior by the CI system, but this is not necessarily something we may want to gate acceptance on, since it would require work to implement and include.
As a result, dropping this down from MUST to SHOULD.
/cc @haydentherapper @kommendorkapten @feelepxyz @asraa @laurentsimon @aladh @marshall007 for any additional feedback
Dropped `Build Signer Digest` OID requirement from `MUST` to `SHOULD`.
✅

oid-info: Drop Build Signer Digest requirement from MUST -> SHOULD

---

docs/oidc.md

This adds some advice for how to choose SANs and some of the considerations.
NONE

oidc.md: Add section for how to select SANs.

---

config/fulcio-config.yaml
federation/gitlab.com/config.yaml
pkg/challenges/challenges.go
pkg/config/config.go
pkg/config/config_test.go
pkg/identity/gitlabcom/issuer.go
pkg/identity/gitlabcom/issuer_test.go
pkg/identity/gitlabcom/principal.go
pkg/identity/gitlabcom/principal_test.go
pkg/server/grpc_server.go
pkg/server/grpc_server_test.go
pkg/server/issuer_pool.go

- Add GitLab.com OIDC to Fulcio
Initial work to support gitlab.com, for self-hosted we will need to discuss how we want to deal with it.
similar work that was done in #890 
sample gitlab pipeline
```yaml
docker-build:
image: docker:latest
stage: build
variables:
COSIGN_EXPERIMENTAL: "true"
id_tokens:
SIGSTORE_JWT:
aud: "sigstore"
before_script:
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
- apk add --update curl && rm -rf /var/cache/apk/*
- curl -L https://github.com/sigstore/cosign/releases/download/v1.13.1/cosign-linux-amd64  -o cosign
- chmod +x cosign
- mv cosign /usr/bin
script:
- cosign sign --identity-token=${SIGSTORE_JWT} registry.gitlab.com/cpanato/testing-cosign:main
```
sample token payload
```json
{
"namespace_id": "1730270",
"namespace_path": …
```

Add GitLab.com OIDC to Fulcio

---

docs/oid-info.md

This removes the unconditional statement that the `iss` claim always appears in this extension, while retaining that behavior for non-federated tokens (and explicitly leaving it ambiguous for federated ones).
CC @haydentherapper
Closes #1145.

docs/oid-info: clarify source of issuer extensions

---

pkg/identity/gitlabcom/principal.go
pkg/server/grpc_server_test.go

This was erroneously set to match the build signer URI. This will eventually be pipeline_ref when it is populated (dependent on https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121597)
BREAKING CHANGE: GitLab Build Config URI claim is temporarily removed. This was erroneously set to an incorrect value that did not match the documentation. This will repopulated once the correct value is available in upstream claims.

gitlab: remove build config URI.

---

cmd/app/grpc.go
cmd/app/grpc_test.go
cmd/app/serve.go

In some deployment scenarios, it may be useful to allow a fulcio instance to listen for gRPC over TLS without the presence of a fronting load balancer. This adds two new command line arguments which allow providing the private key and certificate that can be used to support enabling TLS on the grpc port
* grpc-port can now listen with TLS support using `--grpc-tls-certificate` and `--grpc-tls-key` command line arguments

configure server-side TLS on grpc listener

---

cmd/app/grpc.go
cmd/app/grpc_test.go

If the PKI material used to expose a TLS endpoint changes while an instance is running, the instance must be restarted to read the new material. This change adds an fsnotify-based watcher for the certificate, and caches the value of the cert in process memory to save file I/O during the establishment of each TLS connection.
This scenario is likely in Kubernetes where PKI material may be refreshed by a renewal process and exposed to Fulcio through a volume mount.

add fsnotify-backed cache for reading TLS PKI material

---

.github/workflows/verify-k8s.yml
cmd/app/grpc.go
cmd/app/http.go
config/deployment.yaml
docker-compose.yml
pkg/server/grpc_server.go
test/prometheus/main.go

This adds both HTTP and gRPC health check endpoints to Fulcio.
HTTP: `/healthz` should return `HTTP 200 OK`
gRPC: implements [gRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md)
This also adds coverage for this via K8S local testing using readiness and liveness probes in cluster.
* HTTP and gRPC health check endpoints are now exposed from Fulcio

add HTTP and GRPC health check endpoints

---

cmd/app/http.go
cmd/app/http_test.go

always use non-TLS credentials to connect over unix domain socket

---

go.mod
go.sum
pkg/config/config.go
pkg/config/config_test.go
pkg/identity/authorize.go
pkg/identity/base/issuer.go
pkg/identity/buildkite/issuer.go
pkg/identity/buildkite/issuer_test.go
pkg/identity/email/issuer.go
pkg/identity/email/issuer_test.go
pkg/identity/github/issuer.go
pkg/identity/github/issuer_test.go
pkg/identity/gitlabcom/issuer.go
pkg/identity/gitlabcom/issuer_test.go
pkg/identity/issuer.go
pkg/identity/issuerpool.go
pkg/identity/issuerpool_test.go
pkg/identity/kubernetes/issuer.go
pkg/identity/kubernetes/issuer_test.go
pkg/identity/spiffe/issuer.go
pkg/identity/spiffe/issuer_test.go
pkg/identity/uri/issuer.go
pkg/identity/uri/issuer_test.go
pkg/identity/username/issuer.go
pkg/identity/username/issuer_test.go

This PR exposes some oidc config options allowed by the go-oidc library that we use, specifically [SkipExpiryCheck](https://github.com/coreos/go-oidc/blob/b203e58c24394ddf5e816706a7645f01280245c7/oidc/verify.go#L96). 
It updates the LRU cache for verifiers to include both the verifier and the config in the cache, so that Verifier A with a normal config can be distinguished from Verifier A with a config with SkipExpiryCheck set

Expose SkipExpiryCheck OIDC Config Option in Verifier

---

tools/loadtest/README.md

Remove deprecated URL, add warning

Update loadtest instructions

---

docs/oid-info.md

This is included in the deprecated group due to a lack of DER encoding and is replaced by `1.3.6.1.4.1.57264.1.8`.
cc @haydentherapper

oid-info: mark old issuer ext as deprecated

---

docs/oid-info.md

This appears to be a DER-encoded string with the ASN.1 UTF8String tag.
Fixes https://github.com/sigstore/fulcio/issues/1301
This seems like an oversight or typo.
NONE
NONE

Include source repo visibility in oid range

---

pkg/server/grpc_server.go

This [PR](https://github.com/sigstore/fulcio/pull/1258/files#diff-648d47fb9eeb444c1a09095dd41e4012ee5aafcb37b712f7f3bf492d8410017dR48) updated the `NewGRPCCAServer` function to return a struct rather than an interface. I think this was done to make it easier to set up the GRPC health server.
We use this function downstream, and it's much more complicated for us to write tests (previously we could mock the `NewGRPCCAServer` function and return a mock interface). 
This PR basically changes back to returning an interface, and creates a new `GRPCCAServer` which embeds the usual fulcio server and the grpc health check server.

Create interface for GRPC server which encompasses the GRPC HealthServer

---

config/fulcio-config.yaml
federation/dev.gitlab.org/config.yaml
federation/ops.gitlab.net/config.yaml

We at GitLab (https://about.gitlab.com) are looking at integrating cosign to our official build and release workflow and are very much interested in using the keyless signing flow for it. However, our builds and releases happen not at GitLab.com, but at two separate GitLab instances - dev.gitlab.org and ops.gitlab.net. This PR adds support for those instances as valid OIDC token providers so that keyless signing and verification can be done in pipelines running on those instances.
As the first step, we will be signing our cloud native Docker images using cosign, and are also thinking about signing other build artifacts in the future.
PS: I referred to https://github.com/sigstore/fulcio/pull/1214 for this PR.
* Support GitLab's build and release instances as OIDC providers

Support GitLab's build and release instances as OIDC providers

---

cmd/app/grpc.go
cmd/app/http.go
cmd/app/http_test.go
cmd/app/serve.go

This catches sigint and sigterm and calls each server's shutdown method, blocking until shutdown completes.
This is only added for non-Duplex, we'll need to add a shutdown method for Duplex servers.
Fixes https://github.com/sigstore/fulcio/issues/1341

Gracefully shutdown HTTP, gRPC, and Prom servers

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder to use go1.21.1 and bump cosign image

update builder to use go1.21.1 and bump cosign image

---

.goreleaser.yml
.ko.yaml

Update to base-debian12
Open questions?

Disable CGO on release builds

---

.github/workflows/validate-release.yml
.github/workflows/verify.yml
release/cloudbuild.yaml

- update builder image to use go1.21.4
- bump golangci-lint to v1.55.x

update builder image to use go1.21.4 and bump golangci-lint to v1.55.x

---

docs/new-idp-requirements.md

Starting a new document to capture the requirements for adding a new IDP to Sigstore Public Deployment as proposed in https://github.com/sigstore/fulcio/issues/397
* Add New IDP Requirements documentation

[DRAFT] Create new-idp-requirements.md

---

docs/how-certificate-issuing-works.md

As part of doc enhancements in ae4c766f, the description in step 7 was removed. Although the final step is simple and the diagram and section header are clear, it is jarring for the final step to be inconsistent with the others by having no text body. It is moreover unfriendly to screen readers since there is no context for the diagram. This change adds the brief description back for the sake of readability.
Enhance the documentation readability by having a consistent flow from step to step.
NONE
n/a

docs: Add back descriptive content on cert issuing

---

Dockerfile
docker-compose.debug.yml

- Update dlv version to be compatible with Go 1.21
- Add required flag --ca to fulcio command
- Switch from "command" to "entrypoint" to override the ENTRYPOINT in the Dockerfile
- Use ports consistent with the main docker-compose file to avoid conflicting with rekor
- Use metrics port environment variable which was missed in ca33c989
NONE

Fix debug docker-compose setup

---

docker-compose.yml

Without this change, when Fulcio is run in docker-compose, signing an artifact may fail with the error "Error entering certificate in CTL". This happens if the docker-compose service have been run previously on the host and the ctfeConfig volume is populated from the last run, so it would generally only be seen in a developer environment. The error happens because the ctfe_init container starts too soon, and ct_server starts with Fulcio's ephemeral root CA from the last run, which is now the wrong CA. This change fixes the issue by ensuring ct_server only starts after ctfe_init has exited successfully, instead of just after it is started. This also means that Fulcio needs to be one of the first services to start so that it can make the ephemeral CA available to download.
NONE

Fix docker-compose service order

---

docs/oidc.md

Added GitLab OIDC provider to the documentation /docs/oidc.md file that was missing. 
The example was copied over from https://docs.sigstore.dev/certificate_authority/oidc-in-fulcio/ documentation.

Added GitLab OIDC Provider documentation

---

pkg/certificate/extensions.go
pkg/certificate/extensions_test.go

Close #1583. The extensions_test.go has also been updated.
Changed the `pkg/certificate/parseExtensions` to be public allowing external Fulcio certificate consumers to parse all x509 extensions into the Extensions struct.
None

Change parseExtension function to be public

---

CHANGELOG.md

Add CHANGELOG for v1.4.4

---

.github/workflows/validate-release.yml
Dockerfile
Dockerfile.ctfe_init
release/cloudbuild.yaml

move to golang 1.21.8 and bump other deps

---

.gitattributes

On Windows the files copied to the docker container's work environment must have lf line endings to be properly executed.
Resolves #1605
On windows, if the dev cloning the repository has autocrlf set to true then sh files will have crlf line endings. When copied into the container they will keep this line ending and result in an error message: "/bin/sh: 1: /root/logid.sh: not found" in the ctfe_init container. 
Forced sh file checkout to lf line endings for windows users. 
No change.

Force sh scripts to checkout with lf line endings

---

CHANGELOG.md

Add changelog for v1.4.5

---

pkg/config/config.go
pkg/server/grpc_server_test.go

Contribute towards #1111 
It updates the logic to support configuration from yaml file. It will be useful for migrating the ci providers onboarding to filling a yaml file instead of creating new modules.
cc @haydentherapper

Adding support for configuration from yaml file

---

cmd/app/http.go

This pull request resolves an issue with the `/healthz` probe failing in environments with a proxy enabled. The probe was using the `0.0.0.0` address for gRPC readiness checks, which could not be filtered by the `NO_PROXY` setting, causing readiness requests to be routed through the proxy and fail. This change updates the probe to use the `localhost` address, ensuring that these requests bypass the proxy and function correctly.
Closes #1704
Updated `/healthz` probe to use localhost for gRPC readiness checks.
No documentation updates are required for this change.

Update /healthz probe to use localhost for gRPC readiness checks

---

.github/workflows/validate-release.yml
.github/workflows/verify.yml
.goreleaser.yml
go.mod
release/cloudbuild.yaml
release/release.mk

- bump builder to go1.22.4 / update golangci-lint and goreleaser config

bump builder to go1.22.4 / update golangci-lint and goreleaser config

---

config/config.jsn
config/fulcio-config.yaml
federation/issuer.enforce.dev/config.yaml
go.mod
go.sum
pkg/config/config.go
pkg/config/config_test.go
pkg/identity/chainguard/issuer.go
pkg/identity/chainguard/issuer_test.go
pkg/identity/chainguard/principal.go
pkg/identity/chainguard/principal_test.go
pkg/server/grpc_server_test.go
pkg/server/issuer_pool.go

This adds support for Chainguard issued tokens, so that users can sign with their Chainguard-issued identity, and so that we can explore signing our own content with our internal service principal construct (see issue).
Related: https://github.com/sigstore/fulcio/issues/1702
Add support for signing with Chainguard-issued tokens.
This is mostly intended for our own use, but I'd be happy to document how folks can make use of this with `chainctl auth token --audience sigstore` if someone points me in the right direction.

Add Chainguard OIDC provider.

---

pkg/identity/chainguard/principal.go
pkg/identity/chainguard/principal_test.go

The cosign logic for interacting with Fulcio treats identity tokens as *largely* opaque, and most of the logic for how issuers and subjects and whatnot is handled happens server-side.  However, for the "proof of possession" `cosign` has some logic (from `sigstore/sigstore`) that fumbles with `email` and `sub` claims in ways that have (until now) been compatible with Fulcio principals.
The Chainguard provider is the first provider that optionally includes an `email` claim, but we always want the subject we use to be our opaque identifier string (from `sub`).  This creates a tear in the fulcio/cosign continuum, and so we must surface what `cosign` is signing as `Name()` even though that isn't necessarily what we embed in the certificate.
The only correct way to implement `Name()` today is …

Surface the right `Name()` from our principal.

---

pkg/certificate/extensions.go
pkg/challenges/challenges.go
pkg/config/config.go
pkg/config/config_network_test.go
pkg/config/config_test.go
pkg/identity/ciprovider/issuer.go
pkg/identity/ciprovider/issuer_test.go
pkg/identity/ciprovider/principal.go
pkg/identity/ciprovider/principal_test.go
pkg/server/grpc_server_test.go
pkg/server/issuer_pool.go

This adds a new generic CI provider so that new CI providers can be added via configuration without any code changes. The existing CI providers will be migrated over.
Ref: https://github.com/sigstore/fulcio/issues/1111
Add back #1679
Signed-off-by: Javan lacerda <javanlacerda@google.com>

CiProvider as a new OIDCIssuer type

---

config/identity/config.yaml

Add Hellō as OIDC provider for email type
#1684 
None
None

add Hellō provider

---

pkg/identity/email/principal_test.go
pkg/oauthflow/oidc.go

Introduces support for `email_verifed` claim to be either a boolean or string value
References https://github.com/sigstore/sigstore/issues/1698
* Boolean and String data type support for `email_verified` claim

Added support for email_verified being a string or bool

---

config/identity/config.yaml

I've caught this bug when validating the rollout in staging. I also did a double check on the other issuers template.

fix claim name for gitlab template

---

config/identity/config.yaml
pkg/identity/ciprovider/issuer_test.go
pkg/identity/ciprovider/principal.go
pkg/identity/ciprovider/principal_test.go

During the validations, we noticed that the the template for `source-repository-ref` for gitlab has a surplus slash.
We also noticed that the error with log `"value <> not present in either claims or defaults.` has spawned several times in production, but we wasn't able to detect the reason for it, then I decided to put at least the issuer that triggered the flow on the error log.
I also added a validation that the metadata should exist for ci-providers.
cc @haydentherapper

fix: removing surplus slash, making logs richer

---

pkg/config/config.go
pkg/config/config_network_test.go
pkg/config/config_test.go
pkg/config/fulcio_config_test.go
pkg/identity/ciprovider/principal.go

It set the ci-provider field for meta-issuers

fix: adding ci provider for meta-issuers

---

config/identity/config.yaml
pkg/identity/ciprovider/principal_test.go

Closes #1770
It set empty string as default value for optional fields on codefresh workflow.

set empty string as defaults for codefresh's optional fields

---

.github/workflows/validate-release.yml
go.mod
release/cloudbuild.yaml

- use go1.22.6 to build fulcio

use go1.22.6 to build fulcio

---

.github/workflows/validate-release.yml
.github/workflows/verify.yml
.golangci.yml
Dockerfile
Dockerfile.ctfe_init
go.mod
pkg/ca/googleca/v1/googleca.go
release/cloudbuild.yaml

upgrade to go1.23

---

.github/workflows/verify-k8s.yml

One of the commit shas referenced a 2 year old commit, which caused CI to fail since it used a deprecated action.

Update chainguard-dev/actions to latest commit

---

cmd/app/serve.go

Closes #1811
The PR #1720 has changed the default config path from `/etc/fulcio-config/config.json` to `/etc/fulcio-config/config.yaml`. This caused problems with non-explicitly configured environments.
Check and fallback to default JSON config if the default YAML configuration file did not exist.

fallback to json default cfg path if yaml does not exist

---

Dockerfile
Dockerfile.ctfe_init
docker-compose.debug.yml
docker-compose.yml

Minor linting changes to Dockerfiles and Docker Compose files.
NONE.
NONE.

style(docker): minor linting changes to Docker files and Docker Compose files

---

config/identity/config.yaml

This PR adds IBM's OIDC provider to the list of providers.
Closes: https://github.com/sigstore/fulcio/issues/1891

config: Add IBM OIDC provider

---

cmd/app/grpc.go
cmd/app/http_test.go
cmd/app/serve.go
cmd/app/serve_test.go
go.mod
go.sum
pkg/server/grpc_server.go
pkg/server/grpc_server_test.go

This PR adds a --client-signing-algorithms flag to Fulcio to restrict what key/hash combinations are allowed.
Closes https://github.com/sigstore/fulcio/issues/1388
This is based on https://github.com/sigstore/fulcio/pull/1517, but I could not mark it as Ready because done by @tetsuo-cpp .

Allow configurable client signing algorithms

---

Dockerfile.dex-idp
docker-compose.yml

Adds a new Dockerfile.dex-idp to use in the docker-compose.yml. This makes the dex-idp more portable to be used in alternate docker-compose from external directories. For example, I may use the service like
```
services:
dex-idp:
build:
context: https://github.com/sigstore/fulcio.git#main
dockerfile: Dockerfile.dex-idp
...
```
https://docs.docker.com/reference/compose-file/build/#attributes
From any directory on the user's system, `docker compose` will do a checkout of the fulcio repo, and build the image with that dockerfile and with that repo  directory as the "docker context". The new dockerfile's `COPY ./config/dex /etc/config/` will build the image with those repo files.
The contents of `./config/dex` are not needed by the other services, and don't need to in a docker "volume". A …

feat: add Dockerfile.dex-idp

---

docker-compose.yml

Same as documented in https://github.com/sigstore/rekor/pull/2473, the MySQL healthcheck was inaccurately reporting healthy when localhost was used. Switching to an address seems to fix it.

Update compose healthcheck for MySQL

---

cmd/app/serve.go
cmd/app/serve_test.go

Registers the `/healthz` endpoint when listening on a duplex http/grpc port, just like the `http` port does when running in non-duplex mode.
The current helm charts use this endpoint for the liveness and readiness probes, so I'm assuming this should be exposed even when HTTP and gRPC are listening on the same port.
Fixes https://github.com/sigstore/fulcio/issues/2047
* /healthz is now exposed when running the HTTP and gRPC servers on the same port.

Register `/healthz` endpoint when listening on duplex http/grpc port

---

pkg/server/error.go

Decide the log level of errors based on the grpc code: client mistakes should not be logged at "error" level.
Fulcio itself currently uses only Internal and InvalidArgument, grpc framework does not use most of the codes listed either: this code still tries to categorize all valid codes in order to be future proof.
Fixes #908.
this client call:
```
$ curl -X POST -d '{}' http://localhost:5555/api/v2/signingCert
{"code":3,"message":"There was an error processing the identity token","details":[]}
```
results in:
```
fulcio-server-1        | 2025-09-10T09:39:58.799Z       WARN    server/error.go:57      oidc: malformed jwt, expected 3 parts got 1     {"requestID": "-03xA5aM", "code": "InvalidArgument", "clientMessage": "There was an error processing the identity token", "error": "oidc: …
```

server: Use warning log level for client errors
