.gitignore, go.mod
=> Init mod and IDE specifics to .gitignore

README.md
=> Fill out the readme a bit.

config/deployment.yaml
=> Switch the ca path to a configmap.

README.md
=> Add permanent link to slack.

README.md
Fix the bullet points around the Security Model section.
=> Minor formatting fix for README.md

cmd/server/app/root.go, go.mod, pkg/api/signing_cert.go, pkg/ctl/ctl.go, pkg/ctl/ctl_test.go
=> CTL Chain Inclusion

cmd/client/app/root.go
Signed-off-by: Bob Callaway <bcallawa@redhat.com>
=> add option to write certs to file

cmd/server/app/root.go, config/deployment.yaml
Signed-off-by: Jake Sanders <jsand@google.com>
=> update default oidc configuration values

README.md
Closes #57 by adding build instructions to the README.
=> add build instruction to README

OWNERS.md
=> Remove Owners file

CODEOWNERS
A mapped GH team exists for this codeowners file
=> Implement codeowners file into fulcio

config/deployment.yaml
=> Rename the service, we already shut down the old one.

cmd/client/app/root.go, openapi.yaml, pkg/api/signing_cert.go, pkg/ca/ca.go, pkg/ca/ca_test.go, pkg/generated/models/certificate_request.go, pkg/generated/restapi/embedded_spec.go
=> RSA support for generated keys.

config/deployment.yaml
=> Drop the dev service entirely.

Dockerfile, config/DEVELOPMENT.md
Update the paths since #91 was merged!
=> Fix paths in Dockerfile for local development

config/deployment.yaml
=> Fix the path in deployment.yaml after the CLI removal.

cmd/app/root.go, cmd/app/serve.go, config/deployment.yaml, config/fulcio-config.yaml, go.mod, go.sum, pkg/config/config.go, pkg/config/config_test.go, pkg/generated/restapi/configure_fulcio_server.go
=> Move OIDC configuration to a nested JSON config file.

README.md
Signed-off-by: Appu Goundan <appu@google.com>
=> Clarify some acronyms, add links

.github/workflows/verify-k8s.yml
=> Resolve CI timeouts

config/deployment.yaml
=> Switch to the JSON logger in prod

README.md
=> Fix misspellings.

cmd/app/root.go
Resolves #152
Signed-off-by: jyotsna-penumaka <jyotsnap@bu.edu>
=> Changes fulcio-server to fulcio

config/fulcio-config.yaml, federation/vstoken.actions.githubusercontent.com/config.yaml
=> Add GitHub OIDC to Fulcio

Makefile
Included -trimpath flag for able to have reproducible builds.
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> Reproducible builds with trimpath

config/DEVELOPMENT.md, pkg/config/config.go
Fixes #235 
Also update the config/DEVELOPMENT.md because it refers to now non-existent cmd/client. So updated to point to cosign.
```release-note
Fixes #235
```
=> Fix nil pointer, update dev docs

.github/workflows/verify-k8s.yml, .ko.yaml
Signed-off-by: Matt Moore <mattomata@gmail.com>
Fixes: https://github.com/sigstore/fulcio/issues/241
```release-note
```
=> Use `CGO_ENABLED=1` via `.ko.yaml`.

pkg/ca/googleca/v1/googleca.go, pkg/ca/googleca/v1beta1/googleca.go
This got dropped unintentionally during the interface refactor in #218 and #220.
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
Fixes
```release-note
```
=> Fix the k8s subject parsing.

pkg/client/client.go, pkg/client/client_test.go
=> add the ability to set the user-agent string on requests from the `Client`

CODEOWNERS
add usersnames list to the codeonwers to make it easier to check
n/a
```release-note
NONE
```
=> add usersnames list to the codeonwers to make it easier to check

cmd/app/createcanocgo.go, pkg/ca/x509ca/x509canocgo.go
Fixes #291
Fixes #291 
```release-note
* Fix building with CGO_ENABLED=0
```
=> Add back support for building with CGO_ENABLED=0

config/DEVELOPMENT.md
* ephemeralca was not documented, so add that to dev docs
* also add documentation for RootCert
* Split out the integration with CTFE since I felt it got lost in the soft hsm steps.
Fixes
```release-note
```
=> Add documentation for testing with `ephemeralca`. Document RootCert method

OID_INFO.md
=> add oid documentation

.github/workflows/scorecard_action.yml
=> add OSSF scorecard action

.github/workflows/validate-release.yml
=> pin one additional set of actions

README.md
file got moved in https://github.com/sigstore/community/pull/42
Fixes
```release-note
```
=> fix link for SECURITY.md

.github/workflows/codeql-analysis.yml, .github/workflows/scorecard_action.yml
=> update to v1.0.29 of codeql-action (including comments)

README.md
As per the title, fixes https://github.com/sigstore/fulcio/issues/360
Signed-off-by: Asra Ali <asraa@google.com>
Fixes
```release-note
```
=> Include instructions to download verify the fulcio root certificate with TUF

config/fulcio-config.yaml, federation/main.go
Add AKS as a meta issuer, now that AKS OIDC Issuer feature is available. 
This was tested using an AKS cluster with the feature `EnableOIDCIssuerPreview` following instruction [here](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#oidc-issuer-preview). 
Signed-off-by: Nghia Tran <tcnghia@gmail.com>
Fixes https://github.com/sigstore/fulcio/issues/231
```release-note
Config change to support AKS per-cluster issuer URLs.
```
=> Add AKS as a meta issuer

README.md
With our GA coming soon, it's time to update this warning! 
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
Fixes
```release-note
```
=> Update warning text.

.github/workflows/validate-release.yml, .goreleaser.yml, Dockerfile, Dockerfile.ctfe_init, release/cloudbuild.yaml
- update cross-build to use go 1.17.7
n/a
```release-note
update cross-build to use go 1.17.7
```
=> update cross-build to use go 1.17.7

docs/oid-info.md
Links in the documentation page were wrong.
```release-note
NONE
```
=> Fixing link to external resources

config/deployment.yaml
Limit the amount of permissions/access allowed for deployments.
Fixes #419 
```release-note
Deployments will now run as non-root and have only read access to root filesystem
```
=> add securityContext to deployment

.github/workflows/verify-k8s.yml, config/README.md, config/deployment.yaml, config/fulcio-config.yaml, config/private-ca-secret-ci.yaml, test/prometheus/main.go
Stop using the -dev suffix for the namespace in the config yamls.
Fixes #417 
```release-note
Config yaml will now create objects in the fulcio namespace instead of fulcio-dev
```
=> drop -dev suffix for namespace and service account.

.github/workflows/verify-k8s.yml, config/deployment.yaml
Streamline the config apply by creating the necessary namespace as part of the yaml.
Fixes
```release-note
```
=> create namespace as part of config yaml

.github/workflows/verify-k8s.yml
=> Take advantage of Chainguard maintained versions of various actions.

.github/workflows/codeql-analysis.yml, .github/workflows/main.yml, .github/workflows/verify-k8s.yml, .github/workflows/verify.yml
Explicitly set permissions to github actions as defaults maybe write-all. read-all default came later.
It is still best to set permissions as explicitly, as any permissions not specified would then default to none.
Fixes
```release-note
```
=> explicitly set permissions for github workflows

release/release.mk
Add missing target name for copy to ghcr.
Fixes
```release-note
```
=> add missing target name for cosign copy 

.github/workflows/validate-release.yml, Dockerfile, Dockerfile.ctfe_init, release/cloudbuild.yaml
- Go update to 1.17.8 and cosign to 1.6.0
n/a
```release-note
Go update to 1.17.8 and cosign to 1.6.0
```
=> Go update to 1.17.8 and cosign to 1.6.0

.github/workflows/validate-release.yml, .goreleaser.yml, Makefile, release/cloudbuild.yaml, release/release.mk
This will generate a YAML artifact for releases.
As I understand it, the current release involves building 5 images, each for a different architecture. With these 5 images, we use docker compose to create a single manifest list from these individual images to support the different architecture. It is this composed image that is signed.
For generating the YAML, we leverage one of the existing ko publish commands, changing it to ko resolve, which generates the YAML. At this point, it will point to one of the single architecture images. After composing the final image, we update the YAML with the manifest list. 
Fixes
```release-note
Generate a release YAML artifact
```
=> Generate release yaml for non-CI builds.

.github/workflows/cut-release.yml
- update action to use git hash
n/a
```release-note
update action to use git hash
```
=> update action to use git hash

.github/workflows/cut-release.yml
- release: dont upload local directory
n/a
```release-note
NONE
```
=> release: dont upload local directory

hack/github-oidc-setup.sh
Cloud build permissions for creating release from GitHub Action Workflow.
Fixes
```release-note
```
=> grant cloud build permissions to github action sa

docs/setup.md
This adds docs for each supported signing backend.
Fixes #302
```release-note
Added documentation for Fulcio signing backends
```
=> Add documentation for setting up Fulcio instance

CODEOWNERS
=> Add @haydentherapper to CODEOWNERS

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update go builder image and cosign image
n/a
```release-note
NONE
```
=> update go builder image and cosign image

release/cloudbuild.yaml
i saw I did a typo here https://github.com/sigstore/fulcio/pull/554 but when I fixed was too late :(
n/a
```release-note
NONE
```
=> fix the digest image

.github/workflows/validate-release.yml, Dockerfile, Dockerfile.ctfe_init, release/cloudbuild.yaml
- update go to 1.17.10
n/a
```release-note
NONE
```
=> update go to 1.17.10

CHANGELOG.md
- add changelog for release v0.5.0
n/a
```release-note
NONE
```
=> add changelog for release v0.5.0

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update go builder and cosign image
`n/a`
`n/a`
=> update go builder and cosign image

CHANGELOG.md
=> Add CHANGELOG for 0.5.2

.github/workflows/scorecard_action.yml, README.md
Enables Scorecard badge beta version for this repo.
NONE
NONE
=> ✨ Enable Scorecard badge

examples/request-certificate/.gitignore, examples/request-certificate/main.go
=> fix example to explicitly set port for gRPC call

.github/workflows/scorecard_action.yml
Signed-off-by: Azeem Shaikh <azeemshaikh38@gmail.com>
v2:alpha adds some bug fixes
NONE
NONE
=> Update scorecard-action to v2:alpha

CHANGELOG.md
- update changelog to add release v0.5.3
=> update changelog to add release v0.5.3

docs/setup.md
Signed-off-by: Hayden B <hblauzvern@google.com>
=> Fix documentation link

CHANGELOG.md
- update previous releases and add notes for v0.6.0
=> update previous releases and add notes for v0.6.0

CHANGELOG.md, DEPRECATIONS.md
Also specify a deprecation for the V1 API. It's short, but I don't want to keep this around for too much longer.
=> Update CHANGELOG for v1.0.0-rc.0

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder image and cosign
=> update builder image and cosign

CHANGELOG.md, README.md
=> 1.0 changelog!

.github/workflows/depsreview.yml
=> remove workflow_dispatch since we don't allow specifying a range

docs/how-certificate-issuing-works.md
=> Fix typo in docs

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder image and cosign image
=> update builder image and cosign image

docs/oid-info.md
Signed-off-by: Hayden B <hblauzvern@google.com>
=> Update OID doc for updating oid-info and timestamp authority OID

cmd/app/grpc.go
I'm trying to use duplex to run Fulcio, and need to pull this function in.
=> Make PassFulcioConfigThruContext function public

.github/workflows/main.yml
Signed-off-by: Hayden B <hblauzvern@google.com>
=> Use repo token for GHA

README.md
Fix typo in README.md eamil -> email
Not applicable
Not applicable
=> Fix typo in README.md eamil -> email

.github/workflows/verify-k8s.yml
=> Update ko action

pkg/server/error.go, pkg/server/grpc_server.go, pkg/server/grpc_server_test.go
Signed-off-by: Hector Fernandez <hector@chainguard.dev>
We realized most of the errors returned the same error message (e.g. genericCAError) when communicating with the CA backend. I added few more error logs and new error types depending on the logic of the error statements.
=> Add custom error logs when communicating with the CA backend

.github/workflows/validate-release.yml, .github/workflows/verify.yml, Dockerfile, Dockerfile.ctfe_init, go.mod, hack/tools/go.mod, release/cloudbuild.yaml
=> Update Fulcio to 1.20

CHANGELOG.md
=> Add CHANGELOG for 1.1.0

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder image to use go1.20.1
=> update builder image to use go1.20.1

.github/workflows/validate-release.yml, .goreleaser.yml, docs/setup.md, release/cloudbuild.yaml, release/release.mk
- update cosign to 2.0.0 and builder image and also cosign flags
=> update cosign to 2.0.0 and builder image and also cosign flags

pkg/identity/buildkite/issuer.go, pkg/identity/buildkite/issuer_test.go
=> implement Issuer interface for buildkite

pkg/identity/base/issuer.go, pkg/identity/base/issuer_test.go, pkg/identity/buildkite/issuer.go, pkg/identity/email/issuer.go, pkg/identity/github/issuer.go, pkg/identity/kubernetes/issuer.go, pkg/identity/spiffe/issuer.go, pkg/identity/uri/issuer.go, pkg/identity/username/issuer.go
Also includes support for regex's in Match for MetaIssuer types
=> Create BaseIssuer type to implement Match for all Issuers

release/cloudbuild.yaml
=> Update cloudbuild for cosign 2.0

CHANGELOG.md
=> Add CHANGELOG for 1.2.0

config/config.jsn, config/fulcio-config.yaml, federation/main.go
GitHub Actions supports enterprise-specific OIDC issuer URLs for security hardening reasons. However, `fulcio` only supports the default issuer URL. Add an additional meta issuer to cover such special-cased issuer URLs.
Resolves sigstore/fulcio#1087.
Added support for GitHub Actions OIDC enterprise-unique issuer URLs.
Don't believe any documentation needs to be updated. https://docs.sigstore.dev/fulcio/oidc-in-fulcio/#source-repository seems fine enough.
=> Support enterprise-unique GitHub Actions OIDC issuer URLs

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- bump cross builder image to use go1.20.3
=> bump cross builder image to use go1.20.3

CHANGELOG.md
=> Add CHANGELOG for 1.3.1

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- Update cross builder and cosign images
=> Update cross builder and cosign images

docs/oid-info.md
Fix spelling, mention that nbf is optional per the OIDC spec
=> Update OID info

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder image to use go1.20.5
=> update builder image to use go1.20.5

config/fulcio-config.yaml, federation/gitlab.archlinux.org/config.yaml
We want to federate so we can sign our container image[1] and perhaps more in the future.
[1] https://gitlab.archlinux.org/archlinux/archlinux-docker/
=> Federate with Arch Linux's GitLab instance

CHANGELOG.md
=> Add CHANGELOG for 1.3.2

CHANGELOG.md
=> changelog for v1.3.3 release

.github/workflows/container-build.yml, Makefile
Similar to what is done in the Rekor project, it would be nice for each commit to main to build a container for testing and/or emergency fixes.
=> add container builds for each push to main

CHANGELOG.md
=> changelog for v1.3.4

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder image to use go1.20.6 and cosign image to 2.1.1
=> update builder image to use go1.20.6 and cosign image to 2.1.1

CHANGELOG.md
=> Add CHANGELOG for 1.4.0

.github/workflows/validate-release.yml, .github/workflows/verify.yml, Dockerfile, Dockerfile.ctfe_init, release/cloudbuild.yaml
=> Upgrade to go1.21

config/fulcio-config.yaml, federation/auth-staging.eclipse.org/config.yaml
=> Add Eclipse staging OIDC provider

SECURITY.md
=> Remove SECURITY.md in favor of org-level policy

DEPRECATIONS.md
Policy link was likely broken when doc refactoring happened.
NONE
=> DEPRECATIONS.md: Fix policy link

cmd/app/serve.go
=> chore: import packages only once

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder image to use go1.21.2
=> update builder image to use go1.21.2

CHANGELOG.md
=> CHANGELOG for v1.4.1

CHANGELOG.md
=> Add changelog for v1.4.3

.github/workflows/codeql-analysis.yml
=> setup build toolchain before running codeql

config/fulcio-config.yaml, federation/auth.eclipse.org/config.yaml
=> Add production OIDC provider for Eclipse

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder image to use go1.21.5
=> update builder image to use go1.21.5

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder to use go1.21.6
=> update builder to use go1.21.6

cmd/app/grpc.go, cmd/app/http.go, cmd/app/serve.go
=> add configurable idle timeout

.github/dependabot.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container-build.yml, .github/workflows/main.yml, .github/workflows/protoc-dependabot-hack.yml, .github/workflows/validate-release.yml, .github/workflows/verify-k8s.yml, .github/workflows/verify.yml, Dockerfile, Dockerfile.ctfe_init, cmd/app/grpc.go, cmd/app/serve.go, cmd/fetch_ca_cert/fetch_ca_cert.go, go.mod, pkg/api/client_test.go, pkg/ca/kmsca/kmsca.go, pkg/log/log.go, pkg/server/grpc_server_test.go, release/cloudbuild.yaml
=> Upgrade go to 1.22

.github/workflows/cut-release.yml
=> switch to community repo of reusable-release

.github/workflows/validate-release.yml, release/cloudbuild.yaml
=> update jobs to use go1.22.3

README.md
xref: https://github.com/sigstore/fulcio/pull/26#issuecomment-2173594812
=> Update slack info

go.mod, go.sum, pkg/server/grpc_server.go, pkg/server/grpc_server_test.go
- replace gopkg.in/square/go-jose.v2 to github.com/go-jose/go-jose/v4
Fixes: https://github.com/sigstore/fulcio/issues/1685
=> replace gopkg.in/square/go-jose.v2 to github.com/go-jose/go-jose/v4

docs/new-idp-requirements.md
This adds policy documentation around requirements for new IDPs.
=> Update IDP requirements

CHANGELOG.md
=> Add changelog for v1.6.0

config/identity/config.yaml, docs/oidc.md
Currently offline and inactive. Spoke offline with maintainer, may add back at a later point
=> Remove allow.pub as identity provider

CHANGELOG.md
=> Add changelog for v1.6.2

CHANGELOG.md
=> Add CHANGELOG for v1.6.3

CHANGELOG.md
=> add changelog for v1.6.4

cmd/create_tink_keyset/create_tink_keyset.go, cmd/fetch_ca_cert/fetch_ca_cert.go, docs/how-certificate-issuing-works.md, go.mod, go.sum, pkg/ca/tinkca/signer.go, pkg/ca/tinkca/signer_test.go, pkg/ca/tinkca/tinkca.go, pkg/ca/tinkca/tinkca_test.go
Now hosted in another org as well.
=> Update Tink library to v2

config/identity/config.yaml
Support for model hub identity provider
=> Add Kaggle identity provider

.github/workflows/verify.yml, go.mod
- Update go min require and golangci-lint
=> Update go min require and golangci-lint

.gitignore, Makefile, README.md, cmd/certificate_maker/certificate_maker.go, docs/certificate-maker.md, pkg/certmaker/certmaker.go, pkg/certmaker/certmaker_test.go, pkg/certmaker/template.go
closes #1930 
makes leaf optional as per @haydentherapper's request as well as updates docs etc.
=> feat: makes leaf optional and other changes. 

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder to use go1.24.1
=> update builder to use go1.24.1

cmd/app/grpc.go, cmd/app/serve.go, go.mod, go.sum, pkg/log/log.go
We only use goa for setting up request ID middleware.
=> Bump goa.design/goa to latest supported version

go.mod, go.sum, hack/tools/go.mod, pkg/config/config.go, pkg/config/config_test.go, pkg/server/error.go, pkg/server/grpc_server.go, pkg/server/grpc_server_test.go, test/prometheus/main.go
Now with generics!
Also fix lint errors.
=> Bump golang-lru to latest version, bump Go toolchain

CHANGELOG.md
=> Add CHANGELOG for v1.7.0

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder image to use go1.24.2
=> update builder image to use go1.24.2

.github/dependabot.yml, docker-compose.yml
Updates to the latest Trillian deps. Also sets the platform explicitly for the MySQL container, which will otherwise fail to startup on macOS since it's looking for ARM rather than emulating AMD64.
=> Update docker compose deps, fix for macOS

cmd/app/http.go
This pull request resolves an issue where internal REST API calls in Fulcio would fail in proxy-enabled environments due to internal gRPC clients connecting to `0.0.0.0:5554`. This address, while valid for server binding, is not appropriate for client connections and is not filtered by `NO_PROXY` settings. As a result, requests were routed through the external proxy and failed. This change updates the client connection address to `localhost`, ensuring requests are properly excluded from proxy routing.
Closes #1987
Fixed internal gRPC client to use `localhost` instead of `0.0.0.0`, avoiding proxy interference in REST-to-gRPC calls.
No documentation updates are required for this change.
=> Use localhost address for internal gRPC client

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder to use go1.24.3
=> update builder to use go1.24.3

.github/workflows/verify.yml
- bump golangci-lint action and version
=> bump golangci-lint action and version

README.md
Update the URL for downloading Sigstore root key from the old path to the new path in the root-signing repository. This ensures users can obtain the correct root key for verification.
NONE
=> docs: update sigstore root key download URL

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- update builder to use go1.24.4
=> update builder to use go1.24.4

.github/workflows/validate-release.yml, release/cloudbuild.yaml
- use go1.24.5 to build fulcio
=> use go1.24.5 to build fulcio
